package internal

import "github.com/coalaura/wtf/types"

func init() {
	types.RegisterSignature(types.Kind7ZipArchive, types.TypeNone, 0, []byte{'7', 'z', 0xbc, 0xaf, 0x27, 0x1c})
	types.RegisterSignature(types.KindACEArchive, types.TypeNone, 7, []byte("**ACE**"))
	types.RegisterSignature(types.KindAINArchive, types.TypeNone, 0, []byte{0x21, 0x12})
	types.RegisterSignature(types.KindAllegroPackfile, types.TypeNone, 0, []byte("slh!"))
	types.RegisterSignature(types.KindAllegroPackfile, types.TypeNone, 0, []byte("slh."))
	types.RegisterSignature(types.KindALZArchive, types.TypeNone, 0, []byte("ALZ\x01"))
	types.RegisterSignature(types.KindAmigaDiskMasher, types.TypeNone, 0, []byte("DMS!"))
	types.RegisterSignature(types.KindAppleArchive, types.TypeNone, 0, []byte("AA01"))
	types.RegisterSignature(types.KindARArchive, types.TypeNone, 0, []byte("!<arch>\n"))
	types.RegisterSignature(types.KindARCArchive, types.TypeNone, 0, []byte{0x1a, 0x02})
	types.RegisterSignature(types.KindARCArchive, types.TypeNone, 0, []byte{0x1a, 0x03})
	types.RegisterSignature(types.KindARCArchive, types.TypeNone, 0, []byte{0x1a, 0x04})
	types.RegisterSignature(types.KindARCArchive, types.TypeNone, 0, []byte{0x1a, 0x08})
	types.RegisterSignature(types.KindARCArchive, types.TypeNone, 0, []byte{0x1a, 0x09})
	types.RegisterSignature(types.KindARCArchive, types.TypeNone, 0, []byte{0x1a, 0x0b})
	types.RegisterSignature(types.KindARJArchive, types.TypeNone, 0, []byte{0x60, 0xea})
	types.RegisterSignature(types.KindBlinkArchive, types.TypeNone, 0, []byte("Blink"))
	types.RegisterSignature(types.KindBzip2Archive, types.TypeNone, 0, []byte("BZh"))
	types.RegisterSignature(types.KindBzip3Archive, types.TypeNone, 0, []byte("BZ3v1"))
	types.RegisterSignature(types.KindCabinetArchive, types.TypeNone, 0, []byte("MSCF"))
	types.RegisterSignature(types.KindCPIOArchive, types.TypeBinaryBigEndian, 0, []byte{0x71, 0xc7})
	types.RegisterSignature(types.KindCPIOArchive, types.TypeBinaryLittleEndian, 0, []byte{0xc7, 0x71})
	types.RegisterSignature(types.KindCPIOArchive, types.TypeNewASCII, 0, []byte("070701"))
	types.RegisterSignature(types.KindCPIOArchive, types.TypeNewASCIIWithCRC, 0, []byte("070702"))
	types.RegisterSignature(types.KindCPIOArchive, types.TypeOldASCII, 0, []byte("070707"))
	types.RegisterSignature(types.KindCrushArchive, types.TypeNone, 0, []byte("CRUSH v"))
	types.RegisterSignature(types.KindCSOArchive, types.TypeNone, 0, []byte("CSO"))
	types.RegisterSignature(types.KindDAXArchive, types.TypeNone, 0, []byte("DAX\x00"))
	types.RegisterSignature(types.KindDebianPackage, types.TypeNone, 0, []byte("!<arch>\ndebian-binary   "))
	types.RegisterSignature(types.KindDSTCompression, types.TypeNone, 0, []byte("DSTb"))
	types.RegisterSignature(types.KindEGGArchive, types.TypeNone, 0, []byte("EGGA"))
	types.RegisterSignature(types.KindFreeArcArchive, types.TypeNone, 0, []byte("ArC\x01"))
	types.RegisterSignature(types.KindGzipArchive, types.TypeNone, 0, []byte{0x1f, 0x8b})
	types.RegisterSignature(types.KindHamarsoftArchive, types.TypeNone, 0, []byte{0x91, 0x33, 0x48, 0x46})
	types.RegisterSignature(types.KindInstallShieldCAB, types.TypeNone, 0, []byte("ISc("))
	types.RegisterSignature(types.KindJarArchive, types.TypeNone, 0, []byte{0x5f, 0x27, 0xa8, 0x89})
	types.RegisterSignature(types.KindJARCSArchive, types.TypeNone, 0, []byte("JARCS\x00"))
	types.RegisterSignature(types.KindJavaPack200, types.TypeNone, 0, []byte{0xca, 0xfe, 0xd0, 0x0d})
	types.RegisterSignature(types.KindKGBArchive, types.TypeNone, 0, []byte("KGB_arch"))
	types.RegisterSignature(types.KindLHAArchive, types.TypeNone, 2, []byte("-lh0-"))
	types.RegisterSignature(types.KindLHAArchive, types.TypeNone, 2, []byte("-lh1-"))
	types.RegisterSignature(types.KindLHAArchive, types.TypeNone, 2, []byte("-lh2-"))
	types.RegisterSignature(types.KindLHAArchive, types.TypeNone, 2, []byte("-lh3-"))
	types.RegisterSignature(types.KindLHAArchive, types.TypeNone, 2, []byte("-lh4-"))
	types.RegisterSignature(types.KindLHAArchive, types.TypeNone, 2, []byte("-lh5-"))
	types.RegisterSignature(types.KindLHAArchive, types.TypeNone, 2, []byte("-lh6-"))
	types.RegisterSignature(types.KindLHAArchive, types.TypeNone, 2, []byte("-lh7-"))
	types.RegisterSignature(types.KindLHAArchive, types.TypeNone, 2, []byte("-lhd-"))
	types.RegisterSignature(types.KindLHAArchive, types.TypeNone, 2, []byte("-lz4-"))
	types.RegisterSignature(types.KindLHAArchive, types.TypeNone, 2, []byte("-lz5-"))
	types.RegisterSignature(types.KindLHAArchive, types.TypeNone, 2, []byte("-lzs-"))
	types.RegisterSignature(types.KindLrzipArchive, types.TypeNone, 0, []byte("LRZI"))
	types.RegisterSignature(types.KindLZ4Frame, types.TypeLZ4Legacy, 0, []byte{0x02, 0x21, 0x4c, 0x18})
	types.RegisterSignature(types.KindLZ4Frame, types.TypeNone, 0, []byte{0x04, 0x22, 0x4d, 0x18})
	types.RegisterSignature(types.KindLZFArchive, types.TypeNone, 0, []byte("ZV\x00"))
	types.RegisterSignature(types.KindLZFArchive, types.TypeNone, 0, []byte("ZV\x01"))
	types.RegisterSignature(types.KindLZFSEData, types.TypeNone, 0, []byte("bvx2"))
	types.RegisterSignature(types.KindLZIPArchive, types.TypeNone, 0, []byte("LZIP"))
	types.RegisterSignature(types.KindLZOPArchive, types.TypeNone, 0, []byte{0x89, 'L', 'Z', 'O', 0x00, 0x0d, 0x0a, 0x1a, 0x0a})
	types.RegisterSignature(types.KindLZXArchive, types.TypeNone, 0, []byte("LZX"))
	types.RegisterSignature(types.KindMArArchive, types.TypeNone, 0, []byte("MAr0\x00"))
	types.RegisterSignature(types.KindMicrosoftCompress, types.TypeNone, 0, []byte("KWAJ\x88\xf0\x27\x33"))
	types.RegisterSignature(types.KindMicrosoftCompress, types.TypeNone, 0, []byte("KWAJ\x88\xf0\x27\xd1"))
	types.RegisterSignature(types.KindMicrosoftCompress, types.TypeNone, 0, []byte("SZDD\x88\xf0\x27\x33"))
	types.RegisterSignature(types.KindMicrosoftCompress, types.TypeSZ, 0, []byte("SZ \x88\xf0'3\xd1"))
	types.RegisterSignature(types.KindMozillaArchive, types.TypeNone, 0, []byte("MAR1\x00"))
	types.RegisterSignature(types.KindMozillaArchive, types.TypeNone, 0, []byte("MARC"))
	types.RegisterSignature(types.KindNeroCDCompilation, types.TypeNone, 0, []byte{0x0e, 'N', 'e', 'r', 'o', 'I', 'S', 'O'})
	types.RegisterSignature(types.KindPeaZipArchive, types.TypeNone, 0, []byte("EA\x01"))
	types.RegisterSignature(types.KindPIMArchive, types.TypeNone, 0, []byte("PIM\x00"))
	types.RegisterSignature(types.KindPKLITEArchive, types.TypeNone, 30, []byte("PKLITE"))
	types.RegisterSignature(types.KindPKSFXArchive, types.TypeNone, 526, []byte("PKSpX"))
	types.RegisterSignature(types.KindPufferArchive, types.TypeNone, 0, []byte("Begin Puffer"))
	types.RegisterSignature(types.KindPufferArchive, types.TypeNone, 0, []byte("PUFX"))
	types.RegisterSignature(types.KindRARArchive, types.TypeRAR5, 0, []byte{'R', 'a', 'r', '!', 0x1a, 0x07, 0x01, 0x00})
	types.RegisterSignature(types.KindRARArchive, types.TypeRARLegacy, 0, []byte{'R', 'a', 'r', '!', 0x1a, 0x07, 0x00})
	types.RegisterSignature(types.KindRNCArchive, types.TypeNone, 0, []byte("RNC\x01"))
	types.RegisterSignature(types.KindRNCArchive, types.TypeNone, 0, []byte("RNC\x02"))
	types.RegisterSignature(types.KindRPMPackage, types.TypeNone, 0, []byte{0xed, 0xab, 0xee, 0xdb})
	types.RegisterSignature(types.KindRubyGemPackage, types.TypeNone, 0, []byte("RubyGems"))
	types.RegisterSignature(types.KindRzipArchive, types.TypeNone, 0, []byte("RZIP"))
	types.RegisterSignature(types.KindSnappyFramedData, types.TypeNone, 0, []byte{0xff, 0x06, 0x00, 0x00, 's', 'N', 'a', 'P', 'p', 'Y'})
	types.RegisterSignature(types.KindSquashFSFilesystem, types.TypeNone, 0, []byte("hsqs"))
	types.RegisterSignature(types.KindSQXArchive, types.TypeNone, 0, []byte("SQX\x00"))
	types.RegisterSignature(types.KindStuffItArchive, types.TypeNone, 0, []byte("SIT!"))
	types.RegisterSignature(types.KindStuffItArchive, types.TypeNone, 0, []byte("SITD"))
	types.RegisterSignature(types.KindStuffItArchive, types.TypeNone, 0, []byte("StuffIt (c)1997-"))
	types.RegisterSignature(types.KindSzipArchive, types.TypeNone, 0, []byte("SZ\x0a\x04"))
	types.RegisterSignature(types.KindUFAArchive, types.TypeNone, 0, []byte("UFA\xc6\xd2\xc1"))
	types.RegisterSignature(types.KindUHAArchive, types.TypeNone, 0, []byte("UHA\x01"))
	types.RegisterSignature(types.KindUHAArchive, types.TypeNone, 0, []byte("UHA\x02"))
	types.RegisterSignature(types.KindUnixCompressArchive, types.TypeNone, 0, []byte{0x1f, 0x9d})
	types.RegisterSignature(types.KindUnixCompressArchive, types.TypeNone, 0, []byte{0x1f, 0xa0})
	types.RegisterSignature(types.KindUUencodedArchive, types.TypeNone, 0, []byte("begin"))
	types.RegisterSignature(types.KindUUencodedArchive, types.TypeNone, 0, []byte("begin-base64"))
	types.RegisterSignature(types.KindWADArchive, types.TypeIWAD, 0, []byte("IWAD"))
	types.RegisterSignature(types.KindWADArchive, types.TypePWAD, 0, []byte("PWAD"))
	types.RegisterSignature(types.KindWindowsImagingFormat, types.TypeNone, 0, []byte("MSWIM\x00\x00\x00"))
	types.RegisterSignature(types.KindXARArchive, types.TypeNone, 0, []byte("xar!"))
	types.RegisterSignature(types.KindXZArchive, types.TypeNone, 0, []byte{0xfd, '7', 'z', 'X', 'Z', 0x00})
	types.RegisterSignature(types.KindZBackup, types.TypeNone, 0, []byte("ZBACKUP\x00"))
	types.RegisterSignature(types.KindZchunk, types.TypeNone, 0, []byte("\x00ZCK1"))
	types.RegisterSignature(types.KindZIPArchive, types.TypeEmpty, 0, []byte{'P', 'K', 5, 6})
	types.RegisterSignature(types.KindZIPArchive, types.TypeNone, 0, []byte{'P', 'K', 7, 8})
	types.RegisterSignature(types.KindZisofsArchive, types.TypeNone, 0, []byte{0x37, 0xe4, 0x53, 0x96, 0xc9, 0xdb, 0xd6, 0x07})
	types.RegisterSignature(types.KindZOOArchive, types.TypeNone, 0, []byte("ZOO "))
	types.RegisterSignature(types.KindZPAQArchive, types.TypeNone, 0, []byte("7kSt"))
	types.RegisterSignature(types.KindZstandardArchive, types.TypeNone, 0, []byte{0x28, 0xb5, 0x2f, 0xfd})
	types.RegisterSignature(types.KindZstandardArchive, types.TypeZstandardSkinnableFrame, 0, []byte{0x50, 0x2a, 0x4d, 0x18})
	types.RegisterSignature(types.KindZstandardDictionary, types.TypeNone, 0, []byte{0x37, 0xa4, 0x30, 0xec})

	types.RegisterMaskedSignature(types.KindGzipData, types.TypeBGZF, 0, []byte{0x1f, 0x8b, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'B', 'C', 0x02, 0x00}, []byte{0xff, 0xff, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0xff, 0xff, 0xff, 0xff})
}
