package internal

import "github.com/coalaura/onda/types"

func init() {
	types.RegisterSignature(types.KindAACAudio, types.TypeADTS, 0, []byte{0xff, 0xf1})
	types.RegisterSignature(types.KindAACAudio, types.TypeADTS, 0, []byte{0xff, 0xf9})
	types.RegisterSignature(types.KindAmigaOctaMED, types.TypeNone, 0, []byte("MMD0"))
	types.RegisterSignature(types.KindAmigaOctaMED, types.TypeNone, 0, []byte("MMD1"))
	types.RegisterSignature(types.KindAmigaOctaMED, types.TypeNone, 0, []byte("MMD2"))
	types.RegisterSignature(types.KindAmigaOctaMED, types.TypeNone, 0, []byte("MMD3"))
	types.RegisterSignature(types.KindAMRAudio, types.TypeNone, 0, []byte("#!AMR\n"))
	types.RegisterSignature(types.KindAMRWBAudio, types.TypeNone, 0, []byte("#!AMR-WB\n"))
	types.RegisterSignature(types.KindAnalogBox, types.TypeNone, 0, []byte("ABox"))
	types.RegisterSignature(types.KindAUAudio, types.TypeNone, 0, []byte(".snd"))
	types.RegisterSignature(types.KindAudacityBlockFile, types.TypeNone, 0, []byte("dns."))
	types.RegisterSignature(types.KindCAFAudio, types.TypeNone, 0, []byte("caff"))
	types.RegisterSignature(types.KindCommodoreSID, types.TypeNone, 0, []byte("PSID"))
	types.RegisterSignature(types.KindCommodoreSID, types.TypeNone, 0, []byte("RSID"))
	types.RegisterSignature(types.KindCsoundMusic, types.TypeNone, 0, []byte("<CsoundSynthesiz"))
	types.RegisterSignature(types.KindDigitalSpeechStandard, types.TypeNone, 0, []byte{0x02, 0x64, 0x73, 0x73})
	types.RegisterSignature(types.KindDigitalSpeechStandard, types.TypeNone, 0, []byte{0x03, 0x64, 0x73, 0x73})
	types.RegisterSignature(types.KindDigitalWatchdogAudio, types.TypeNone, 0, []byte("~t,\x01Pp\x02MR"))
	types.RegisterSignature(types.KindDigitalWatchdogAudio, types.TypeNone, 0, []byte{0x7e, 0x74, 0x2c, 0x01, 0x50, 0x70, 0x02, 0x4d, 0x52})
	types.RegisterSignature(types.KindDreamcastAudio, types.TypeNone, 0, []byte{0x80, 0x00, 0x00, 0x20, 0x03, 0x12, 0x04})
	types.RegisterSignature(types.KindDSFAudio, types.TypeNone, 0, []byte("DSD "))
	types.RegisterSignature(types.KindDTSAudio, types.TypeNone, 0, []byte{0x1f, 0xff, 0xe8, 0x00})
	types.RegisterSignature(types.KindDTSAudio, types.TypeNone, 0, []byte{0x7f, 0xfe, 0x80, 0x01})
	types.RegisterSignature(types.KindDTSAudio, types.TypeNone, 0, []byte{0xfe, 0x7f, 0x01, 0x80})
	types.RegisterSignature(types.KindDTSAudio, types.TypeNone, 0, []byte{0xff, 0x1f, 0x00, 0xe8})
	types.RegisterSignature(types.KindExtensibleMusicFormat, types.TypeNone, 0, []byte("XMF_"))
	types.RegisterSignature(types.KindFastTracker2ExtendedInstrument, types.TypeNone, 0, []byte("Extended Instrument: "))
	types.RegisterSignature(types.KindFastTrackerModule, types.TypeNone, 0, []byte("Extended Module: "))
	types.RegisterSignature(types.KindFLACAudio, types.TypeNone, 0, []byte("fLaC"))
	types.RegisterSignature(types.KindFLStudioProject, types.TypeNone, 0, []byte("FLhd"))
	types.RegisterSignature(types.KindGameBoySound, types.TypeNone, 0, []byte("GBS "))
	types.RegisterSignature(types.KindIFFContainer, types.TypeNone, 0, []byte("FORM"))
	types.RegisterSignature(types.KindImpulseTrackerInstrument, types.TypeNone, 0, []byte("IMPI"))
	types.RegisterSignature(types.KindImpulseTrackerModule, types.TypeNone, 0, []byte("IMPM"))
	types.RegisterSignature(types.KindImpulseTrackerSample, types.TypeNone, 0, []byte("IMPS"))
	types.RegisterSignature(types.KindKorgAudio, types.TypeNone, 0, []byte("KORG"))
	types.RegisterSignature(types.KindMIDISequence, types.TypeNone, 0, []byte("MThd"))
	types.RegisterSignature(types.KindMonkeysAudio, types.TypeNone, 0, []byte("MAC "))
	types.RegisterSignature(types.KindMPEGAudio, types.TypeMP3ID3Tagged, 0, []byte("ID3"))
	types.RegisterSignature(types.KindMusepackAudio, types.TypeStreamVersion7, 0, []byte("MP+"))
	types.RegisterSignature(types.KindMusepackAudio, types.TypeStreamVersion8, 0, []byte("MPCK"))
	types.RegisterSignature(types.KindNESSoundFormat, types.TypeNone, 0, []byte("NESM\x1a"))
	types.RegisterSignature(types.KindNISTSPHEREAudio, types.TypeNone, 0, []byte("NIST_1A"))
	types.RegisterSignature(types.KindOptimFROGAudio, types.TypeNone, 0, []byte("OFR "))
	types.RegisterSignature(types.KindPlaylistFile, types.TypeNone, 0, []byte("[playlist]"))
	types.RegisterSignature(types.KindPlayStationSoundFormat, types.TypeNone, 0, []byte("PSF\x01"))
	types.RegisterSignature(types.KindPlayStationSoundFormat, types.TypeNone, 0, []byte("PSF\x02"))
	types.RegisterSignature(types.KindPlayStationSoundFormat, types.TypeNone, 0, []byte("PSF\x11"))
	types.RegisterSignature(types.KindPlayStationSoundFormat, types.TypeNone, 0, []byte("PSF\x12"))
	types.RegisterSignature(types.KindPlayStationSoundFormat, types.TypeNone, 0, []byte("PSF\x21"))
	types.RegisterSignature(types.KindPlayStationSoundFormat, types.TypeNone, 0, []byte("PSF\x22"))
	types.RegisterSignature(types.KindPlayStationSoundFormat, types.TypeNone, 0, []byte("PSF\x24"))
	types.RegisterSignature(types.KindPlayStationSoundFormat, types.TypeNone, 0, []byte("PSF\x41"))
	types.RegisterSignature(types.KindRKAudio, types.TypeNone, 0, []byte("RKA "))
	types.RegisterSignature(types.KindScreamTrackerModule, types.TypeNone, 44, []byte("SCRM"))
	types.RegisterSignature(types.KindShortenAudio, types.TypeNone, 0, []byte("ajkg"))
	types.RegisterSignature(types.KindSkypeData, types.TypeNone, 0, []byte("#!SILK\n"))
	types.RegisterSignature(types.KindSNESSPC, types.TypeNone, 0, []byte("SNES-SPC700 Sound File Data"))
	types.RegisterSignature(types.KindSonicFoundryAcid, types.TypeNone, 0, []byte("riff"))
	types.RegisterSignature(types.KindSonyCompressedVoice, types.TypeNone, 0, []byte("MS_VOICE"))
	types.RegisterSignature(types.KindSonyOpenMG, types.TypeNone, 0, []byte("ea3\x03"))
	types.RegisterSignature(types.KindSonyWave64Audio, types.TypeNone, 0, []byte("riff\x2e\x91\xcf\x11\xa5\xd6\x28\xdb\x04\xc1\x00\x00"))
	types.RegisterSignature(types.KindSprintMusicStore, types.TypeNone, 0, []byte("ID3\x03\x00\x00\x00"))
	types.RegisterSignature(types.KindTAKAudio, types.TypeNone, 0, []byte("tBaK"))
	types.RegisterSignature(types.KindTTAAudio, types.TypeNone, 0, []byte("TTA1"))
	types.RegisterSignature(types.KindUndergroundAudio, types.TypeNone, 0, []byte("SCHl"))
	types.RegisterSignature(types.KindVideoGameMusic, types.TypeNone, 0, []byte("Vgm "))
	types.RegisterSignature(types.KindVocaloidProject, types.TypeNone, 0, []byte("VPR\x00"))
	types.RegisterSignature(types.KindVocaloidProject, types.TypeNone, 0, []byte("VSQ3"))
	types.RegisterSignature(types.KindVocaloidProject, types.TypeNone, 0, []byte("VSQ4"))
	types.RegisterSignature(types.KindVOCAudio, types.TypeNone, 0, []byte("Creative Voice File\x1a"))
	types.RegisterSignature(types.KindWalkmanMP3, types.TypeNone, 0, []byte("WMMP"))
	types.RegisterSignature(types.KindWavPackAudio, types.TypeNone, 0, []byte("wvpk"))
	types.RegisterSignature(types.KindWavPackCorrection, types.TypeNone, 0, []byte("wvpc"))
	types.RegisterSignature(types.KindYamahaSMAF, types.TypeNone, 0, []byte("MMMD"))

	types.RegisterMaskedSignature(types.KindDSDIFFAudio, types.TypeNone, 0, []byte("FORM\x00\x00\x00\x00FRM8"), []byte{0xff, 0xff, 0xff, 0xff, 0, 0, 0, 0, 0xff, 0xff, 0xff, 0xff})
	types.RegisterMaskedSignature(types.KindIFFContainer, types.TypeAIFCAudio, 0, []byte("FORM\x00\x00\x00\x00AIFC"), []byte{0xff, 0xff, 0xff, 0xff, 0, 0, 0, 0, 0xff, 0xff, 0xff, 0xff})
	types.RegisterMaskedSignature(types.KindIFFContainer, types.TypeAIFFAudio, 0, []byte("FORM\x00\x00\x00\x00AIFF"), []byte{0xff, 0xff, 0xff, 0xff, 0, 0, 0, 0, 0xff, 0xff, 0xff, 0xff})
	types.RegisterMaskedSignature(types.KindRIFFContainer, types.TypeCDAAudio, 0, []byte("RIFF\x00\x00\x00\x00CDDA"), []byte{0xff, 0xff, 0xff, 0xff, 0x00, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff})
	types.RegisterMaskedSignature(types.KindRIFFContainer, types.TypeDownloadableSounds, 0, []byte("RIFF\x00\x00\x00\x00DLS "), []byte{0xff, 0xff, 0xff, 0xff, 0x00, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff})
	types.RegisterMaskedSignature(types.KindRIFFContainer, types.TypeQCPAudio, 0, []byte("RIFF\x00\x00\x00\x00QLCM"), []byte{0xff, 0xff, 0xff, 0xff, 0x00, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff})
	types.RegisterMaskedSignature(types.KindRIFFContainer, types.TypeRIFFMIDI, 0, []byte("RIFF\x00\x00\x00\x00RMID"), []byte{0xff, 0xff, 0xff, 0xff, 0x00, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff})
	types.RegisterMaskedSignature(types.KindRIFFContainer, types.TypeSoundFont2, 0, []byte("RIFF\x00\x00\x00\x00sfbk"), []byte{0xff, 0xff, 0xff, 0xff, 0x00, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff})
	types.RegisterMaskedSignature(types.KindRIFFContainer, types.TypeWAVAudio, 0, []byte("RIFF\x00\x00\x00\x00WAVE"), []byte{0xff, 0xff, 0xff, 0xff, 0x00, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff})
}
