package internal

import "github.com/coalaura/wtf/types"

func init() {
	types.RegisterSignature(types.KindAntennaData, types.TypeNone, 0, []byte("REVNUM:,"))
	types.RegisterSignature(types.KindAOLData, types.TypeNone, 0, []byte("AOL Feed"))
	types.RegisterSignature(types.KindAOLData, types.TypeNone, 0, []byte("AOL"))
	types.RegisterSignature(types.KindAOLData, types.TypeNone, 0, []byte("AOLDB"))
	types.RegisterSignature(types.KindAOLData, types.TypeNone, 0, []byte("AOLIDX"))
	types.RegisterSignature(types.KindAOLData, types.TypeNone, 0, []byte("AOLINDEX"))
	types.RegisterSignature(types.KindAOLData, types.TypeNone, 0, []byte("AOLVM100"))
	types.RegisterSignature(types.KindAOLHistory, types.TypeNone, 0, []byte{0xd4, 0x2a})
	types.RegisterSignature(types.KindAOLParameterInfo, types.TypeNone, 0, []byte("ACSD"))
	types.RegisterSignature(types.KindApproachIndex, types.TypeNone, 0, []byte{0x03, 0x00, 0x00, 0x00, 'A', 'P', 'P', 'R'})
	types.RegisterSignature(types.KindAVG6IntegrityDatabase, types.TypeNone, 0, []byte("AVG6_Int"))
	types.RegisterSignature(types.KindBCFData, types.TypeNone, 0, []byte("BCF\x02"))
	types.RegisterSignature(types.KindBerkeleyDB, types.TypeLittleEndian, 0, []byte{0x53, 0x22, 0x04, 0x00})
	types.RegisterSignature(types.KindBerkeleyDB, types.TypeLittleEndian, 0, []byte{0x61, 0x15, 0x06, 0x00})
	types.RegisterSignature(types.KindBerkeleyDB, types.TypeLittleEndian, 0, []byte{0x62, 0x31, 0x05, 0x00})
	types.RegisterSignature(types.KindBerkeleyDB, types.TypeLittleEndian, 0, []byte{0x88, 0x09, 0x04, 0x00})
	types.RegisterSignature(types.KindBerkeleyDB, types.TypeNone, 0, []byte{0x00, 0x04, 0x09, 0x88})
	types.RegisterSignature(types.KindBerkeleyDB, types.TypeNone, 0, []byte{0x00, 0x04, 0x22, 0x53})
	types.RegisterSignature(types.KindBerkeleyDB, types.TypeNone, 0, []byte{0x00, 0x05, 0x31, 0x62})
	types.RegisterSignature(types.KindBerkeleyDB, types.TypeNone, 0, []byte{0x00, 0x06, 0x15, 0x61})
	types.RegisterSignature(types.KindBGBlitzDatabase, types.TypeNone, 0, []byte{0xac, 0xed, 0x00, 0x05, 0x73, 0x72, 0x00, 0x12})
	types.RegisterSignature(types.KindBitcoinWallet, types.TypeNone, 8, []byte{0x62, 0x31, 0x05, 0x00, 0x09, 0x00, 0x00, 0x00, 0x00, 0x20, 0x00, 0x00, 0x00, 0x09, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00})
	types.RegisterSignature(types.KindBUFR, types.TypeNone, 0, []byte("BUFR"))
	types.RegisterSignature(types.KindDB2Conversion, types.TypeNone, 0, []byte("SQLOCONV"))
	types.RegisterSignature(types.KindFeatherData, types.TypeNone, 0, []byte("FEA1"))
	types.RegisterSignature(types.KindFiascoDatabase, types.TypeNone, 0, []byte("FDBH\x00"))
	types.RegisterSignature(types.KindFirebirdDatabase, types.TypeNone, 0, []byte{0x01, 0x00, 0x39, 0x30})
	types.RegisterSignature(types.KindFITActivity, types.TypeNone, 8, []byte(".FIT"))
	types.RegisterSignature(types.KindGDBMDatabase, types.TypeNone, 0, []byte{0x13, 0x57, 0x9a, 0xcd})
	types.RegisterSignature(types.KindGDBMDatabase, types.TypeNone, 0, []byte{0x13, 0x57, 0x9a, 0xce})
	types.RegisterSignature(types.KindGDBMDatabase, types.TypeNone, 0, []byte{0x13, 0x57, 0x9a, 0xcf})
	types.RegisterSignature(types.KindGDBMDatabase, types.TypeNone, 0, []byte{0xcd, 0x9a, 0x57, 0x13})
	types.RegisterSignature(types.KindGDBMDatabase, types.TypeNone, 0, []byte{0xce, 0x9a, 0x57, 0x13})
	types.RegisterSignature(types.KindGDBMDatabase, types.TypeNone, 0, []byte{0xcf, 0x9a, 0x57, 0x13})
	types.RegisterSignature(types.KindGHCiInterface, types.Type32Bit, 0, []byte{0x1d, 0xfa, 0xce, 0x10})
	types.RegisterSignature(types.KindGHCiInterface, types.Type64Bit, 0, []byte{0x1d, 0xfa, 0xce, 0x14})
	types.RegisterSignature(types.KindGitBundle, types.TypeNone, 0, []byte("# v2 git bundle\n"))
	types.RegisterSignature(types.KindGitBundle, types.TypeNone, 0, []byte("# v3 git bundle\n"))
	types.RegisterSignature(types.KindGitCommitGraph, types.TypeNone, 0, []byte{'C', 'G', 'P', 'H'})
	types.RegisterSignature(types.KindGitPackBitmap, types.TypeNone, 0, []byte{'B', 'I', 'T', 'M'})
	types.RegisterSignature(types.KindGitPackIndex, types.TypeNone, 0, []byte("\xfftOc"))
	types.RegisterSignature(types.KindGitPackReverseIndex, types.TypeNone, 0, []byte{'R', 'I', 'D', 'X'})
	types.RegisterSignature(types.KindGNUGettextMachineCatalog, types.TypeNone, 0, []byte{0x95, 0x04, 0x12, 0xde})
	types.RegisterSignature(types.KindGNUGettextMachineCatalog, types.TypeNone, 0, []byte{0xde, 0x12, 0x04, 0x95})
	types.RegisterSignature(types.KindHadoopRCFile, types.TypeNone, 0, []byte("RCF"))
	types.RegisterSignature(types.KindHadoopSequenceFile, types.TypeNone, 0, []byte("SEQ6"))
	types.RegisterSignature(types.KindHDF4Data, types.TypeNone, 0, []byte{0x0e, 0x03, 0x13, 0x01})
	types.RegisterSignature(types.KindKyotoCabinetDatabase, types.TypeNone, 0, []byte("KCDB"))
	types.RegisterSignature(types.KindLidarData, types.TypeNone, 0, []byte("LASF"))
	types.RegisterSignature(types.KindLotusNotesDatabase, types.TypeNone, 0, []byte{0x1a, 0x00, 0x00, 0x04, 0x00, 0x00})
	types.RegisterSignature(types.KindLotusNotesDatabaseTemplate, types.TypeNone, 0, []byte{0x1a, 0x00, 0x00})
	types.RegisterSignature(types.KindLuceneIndex, types.TypeNone, 0, []byte("?LUCENE"))
	types.RegisterSignature(types.KindMATLABData, types.TypeNone, 0, []byte("MATLAB 5.0 MAT-file"))
	types.RegisterSignature(types.KindMicrosoftMoney, types.TypeNone, 0, []byte{0x00, 0x01, 0x00, 0x00, 'M', 'S', 'I', 'S', 'A', 'M', ' ', 'D', 'a', 't', 'a', 'b', 'a', 's', 'e'})
	types.RegisterSignature(types.KindMicrosoftSQLServerDatabase, types.TypeNone, 0, []byte{0x01, 0x0f, 0x00, 0x00, 0x08, 0x02, 0x00, 0x00})
	types.RegisterSignature(types.KindMultiBitBlockchain, types.TypeNone, 0, []byte("SPVB"))
	types.RegisterSignature(types.KindMultiBitInfo, types.TypeNone, 0, []byte("multiBit.info"))
	types.RegisterSignature(types.KindMultiBitWallet, types.TypeNone, 0, []byte{0x0a, 0x16, 0x6f, 0x72, 0x67, 0x2e, 0x62, 0x69, 0x74, 0x63, 0x6f, 0x69, 0x6e, 0x2e, 0x70, 0x72})
	types.RegisterSignature(types.KindMySQLMyISAM, types.TypeNone, 0, []byte{0xfe, 0xfe, 0x07})
	types.RegisterSignature(types.KindNumPyArray, types.TypeNone, 0, []byte("\x93NUMPY"))
	types.RegisterSignature(types.KindOCamlObject, types.TypeNone, 0, []byte("Caml1999O"))
	types.RegisterSignature(types.KindPalmData, types.TypeNone, 0, []byte("\xbe\xba\xfe\xca\x0fPalmSG Data"))
	types.RegisterSignature(types.KindPalmData, types.TypeNone, 0, []byte("DBFH"))
	types.RegisterSignature(types.KindPalmData, types.TypeNone, 0, []byte{0x00, 0x01, 0x42, 0x41})
	types.RegisterSignature(types.KindPalmData, types.TypeNone, 0, []byte{0x00, 0x01, 0x42, 0x44})
	types.RegisterSignature(types.KindPRTGDatabase, types.TypeNone, 0, []byte{0x00, 0x3b, 0x05, 0x00, 0x01, 0x00, 0x00, 0x00})
	types.RegisterSignature(types.KindPsiwtftabase, types.TypeNone, 0, []byte("OPLDatab"))
	types.RegisterSignature(types.KindPythonPickle, types.TypeNone, 0, []byte{0x80, 0x03})
	types.RegisterSignature(types.KindPythonPickle, types.TypeNone, 0, []byte{0x80, 0x04})
	types.RegisterSignature(types.KindPythonPickle, types.TypeNone, 0, []byte{0x80, 0x05})
	types.RegisterSignature(types.KindQDBMDatabase, types.TypeNone, 0, []byte("[QDBM]"))
	types.RegisterSignature(types.KindQuickenData, types.TypeNone, 0, []byte("QEL "))
	types.RegisterSignature(types.KindQuickenData, types.TypeNone, 0, []byte("QW Ver. "))
	types.RegisterSignature(types.KindQuickenData, types.TypeNone, 0, []byte{0xac, 0x9e, 0xbd, 0x8f, 0x00, 0x00})
	types.RegisterSignature(types.KindQuickenQuickFinder, types.TypeNone, 0, []byte{0x50, 0x00, 0x00, 0x00, 0x20, 0x00, 0x00, 0x00})
	types.RegisterSignature(types.KindRData, types.TypeNone, 0, []byte("RDX2\n"))
	types.RegisterSignature(types.KindRData, types.TypeNone, 0, []byte("RDX3\n"))
	types.RegisterSignature(types.KindROOTData, types.TypeNone, 0, []byte("root"))
	types.RegisterSignature(types.KindRubyMarshal, types.TypeNone, 0, []byte{0x04, 0x08})
	types.RegisterSignature(types.KindSASData, types.TypeNone, 0, []byte("HEADER RECORD***"))
	types.RegisterSignature(types.KindSASData, types.TypeNone, 12, []byte{0xc2, 0xea, 0x81, 0x60, 0xb3, 0x14, 0x11, 0xcf, 0xbd, 0x92, 0x08, 0x00, 0x09, 0xc7, 0x31, 0x8c, 0x18, 0x1f, 0x10, 0x11})
	types.RegisterSignature(types.KindSkypeLocalization, types.TypeNone, 0, []byte("MLSW"))
	types.RegisterSignature(types.KindSPSSData, types.TypeNone, 0, []byte("$FL2"))
	types.RegisterSignature(types.KindSPSSPortableData, types.TypeNone, 0, []byte("SPSSPORT"))
	types.RegisterSignature(types.KindStataData, types.TypeNone, 0, []byte("<stata_dta>"))
	types.RegisterSignature(types.KindTensorFlowLiteModel, types.TypeNone, 4, []byte("TFL3"))
	types.RegisterSignature(types.KindTheBatIndex, types.TypeNone, 0, []byte{0x01, 0x01, 0x47, 0x19, 0xa4, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00})
	types.RegisterSignature(types.KindTokyoCabinetDatabase, types.TypeNone, 0, []byte("ToCa"))
	types.RegisterSignature(types.KindWiredTigerDatabase, types.TypeNone, 0, []byte("WiredTiger\x00"))
	types.RegisterSignature(types.KindXilinxBitstream, types.TypeNone, 0, []byte{0x00, 0x09, 0x0f, 0xf0, 0x0f, 0xf0, 0x0f, 0xf0, 0x0f, 0xf0, 0x00, 0x00, 0x01, 0x61})
}
