package internal

import "github.com/coalaura/wtf/types"

func init() {
	types.RegisterSignature(types.KindAcronisTrueImage, types.TypeNone, 0, []byte{0xce, 0x24, 0xb5, 0xa0})
	types.RegisterSignature(types.KindAcronisTrueImage, types.TypeVersionB4, 0, []byte{0xb4, 0x6e, 0x68, 0x44})
	types.RegisterSignature(types.KindAcronisTrueImage, types.TypeVersionCE, 0, []byte{0xce, 0x24, 0xb9, 0xa2, 0x20, 0x00, 0x00, 0x00})
	types.RegisterSignature(types.KindAndroidSparseImage, types.TypeNone, 0, []byte{0x3a, 0xff, 0x26, 0xed})
	types.RegisterSignature(types.KindAPFSFilesystem, types.TypeNone, 32, []byte("NXSB"))
	types.RegisterSignature(types.KindAppleDiskImage, types.TypeNone, 0, []byte("cdsaencr"))
	types.RegisterSignature(types.KindAppleDiskImage, types.TypeNone, 0, []byte("encrcdsa"))
	types.RegisterSignature(types.KindAppleDiskImage, types.TypeNone, 0, []byte{0x78, 0x01, 0x73, 0x0d, 0x62, 0x62, 0x60})
	types.RegisterSignature(types.KindAppleISOHybridDiskImage, types.TypeNone, 0, []byte{'E', 'R', 0x02, 0x00, 0x00})
	types.RegisterSignature(types.KindBcachefsFilesystem, types.TypeNone, 4096, []byte{0xc6, 0x85, 0x73, 0xf6, 0x4e, 0x1a, 0x45, 0xca, 0x82, 0x65, 0xf5, 0x7f, 0x48, 0xba, 0x6d, 0x81})
	types.RegisterSignature(types.KindBeFSFilesystem, types.TypeNone, 512, []byte("1SFB"))
	types.RegisterSignature(types.KindBeFSFilesystem, types.TypeNone, 512, []byte("BFS1"))
	types.RegisterSignature(types.KindBitLockerDiskEncryption, types.TypeNone, 3, []byte("-FVE-FS-"))
	types.RegisterSignature(types.KindBochsDiskImage, types.TypeNone, 0, []byte("Bochs Virtual HD Image"))
	types.RegisterSignature(types.KindBtrfsFilesystem, types.TypeNone, 0x10040, []byte("_BHRfS_M"))
	types.RegisterSignature(types.KindCramFSFilesystem, types.TypeNone, 0, []byte{0x45, 0x3d, 0xcd, 0x28})
	types.RegisterSignature(types.KindDolphinRVZImage, types.TypeNone, 0, []byte("RVZ\x01"))
	types.RegisterSignature(types.KindExFATFilesystem, types.TypeNone, 3, []byte("EXFAT   "))
	types.RegisterSignature(types.KindF2FSFilesystem, types.TypeNone, 1024, []byte{0x10, 0x20, 0xf5, 0xf2})
	types.RegisterSignature(types.KindGUIDPartitionTable, types.TypeNone, 512, []byte("EFI PART"))
	types.RegisterSignature(types.KindHFSPlusFilesystem, types.TypeNone, 1024, []byte("H+"))
	types.RegisterSignature(types.KindHFSPlusFilesystem, types.TypeNone, 1024, []byte("HX"))
	types.RegisterSignature(types.KindISO9660DiskImage, types.TypeNone, 0x8001, []byte("CD001"))
	types.RegisterSignature(types.KindJFFS2Filesystem, types.TypeNone, 0, []byte{0x85, 0x19})
	types.RegisterSignature(types.KindJFSFilesystem, types.TypeNone, 32768, []byte("JFS1"))
	types.RegisterSignature(types.KindLinuxSwapSpace, types.TypeNone, 4086, []byte("SWAP-SPACE"))
	types.RegisterSignature(types.KindLinuxSwapSpace, types.TypeNone, 4086, []byte("SWAPSPACE2"))
	types.RegisterSignature(types.KindLUKS2DiskEncryption, types.TypeNone, 0, []byte{'S', 'K', 'U', 'L', 0xba, 0xbe})
	types.RegisterSignature(types.KindLUKSDiskEncryption, types.TypeNone, 0, []byte{'L', 'U', 'K', 'S', 0xba, 0xbe})
	types.RegisterSignature(types.KindMacriumReflectDiskImage, types.TypeNone, 0, []byte("REFLECT "))
	types.RegisterSignature(types.KindNILFS2Filesystem, types.TypeNone, 1032, []byte{0x02, 0x09, 0x01, 0x12})
	types.RegisterSignature(types.KindNTFSFilesystem, types.TypeNone, 3, []byte("NTFS    "))
	types.RegisterSignature(types.KindParallelsDiskImage, types.TypeNone, 0, []byte("WithoutBorders"))
	types.RegisterSignature(types.KindPGPDiskImage, types.TypeNone, 0, []byte("PGPdMAIN"))
	types.RegisterSignature(types.KindPowerISODirectAccessArchive, types.TypeNone, 0, []byte("DAA\x00\x00\x00\x00\x00"))
	types.RegisterSignature(types.KindPowerISODirectAccessArchive, types.TypeNone, 0, []byte("DAA\x1a"))
	types.RegisterSignature(types.KindQCOWDiskImage, types.TypeVersion1, 0, []byte{'Q', 'F', 'I', 0xfb, 0x00, 0x00, 0x00, 0x01})
	types.RegisterSignature(types.KindQCOWDiskImage, types.TypeVersion2, 0, []byte{'Q', 'F', 'I', 0xfb, 0x00, 0x00, 0x00, 0x02})
	types.RegisterSignature(types.KindQCOWDiskImage, types.TypeVersion3, 0, []byte{'Q', 'F', 'I', 0xfb, 0x00, 0x00, 0x00, 0x03})
	types.RegisterSignature(types.KindQEMUQEDDiskImage, types.TypeNone, 0, []byte("QED\x00"))
	types.RegisterSignature(types.KindQNX4Filesystem, types.TypeNone, 512, []byte("QNX4FS"))
	types.RegisterSignature(types.KindQNX6Filesystem, types.TypeNone, 8192, []byte("QNX6FS"))
	types.RegisterSignature(types.KindReFSFilesystem, types.TypeNone, 3, []byte("ReFS\x00"))
	types.RegisterSignature(types.KindReiserFSFilesystem, types.TypeNone, 65588, []byte("ReIsEr2Fs"))
	types.RegisterSignature(types.KindReiserFSFilesystem, types.TypeNone, 65588, []byte("ReIsEr3Fs"))
	types.RegisterSignature(types.KindReiserFSFilesystem, types.TypeNone, 65588, []byte("ReIsEr4"))
	types.RegisterSignature(types.KindReiserFSFilesystem, types.TypeNone, 65588, []byte("ReIsErFs"))
	types.RegisterSignature(types.KindROMFSFilesystem, types.TypeNone, 0, []byte("-rom1fs-"))
	types.RegisterSignature(types.KindRuntimeSoftwareDiskImage, types.TypeNone, 0, []byte("RTS COM"))
	types.RegisterSignature(types.KindRuntimeSoftwareDiskImage, types.TypeNone, 0, []byte{0x1a, 'R', 'T', 'S', ' ', 'C', 'O', 'M'})
	types.RegisterSignature(types.KindSteganosVirtualDrive, types.TypeNone, 0, []byte("ACv"))
	types.RegisterSignature(types.KindSymantecGhostDiskImage, types.TypeNone, 0, []byte{0xfe, 0xef, 0x01, 0x01})
	types.RegisterSignature(types.KindSymantecGhostDiskImage, types.TypeNone, 0, []byte{0xfe, 0xef, 0x02, 0x01})
	types.RegisterSignature(types.KindTeraByteDiskImage, types.TypeNone, 0, []byte{0x00, 0x00, 0x00, 0x00, 0x14, 0x00, 0x00, 0x00})
	types.RegisterSignature(types.KindUBIFSFilesystem, types.TypeNone, 0, []byte{0x31, 0x18, 0x10, 0x06})
	types.RegisterSignature(types.KindUFSFilesystem, types.TypeNone, 1372, []byte{0x00, 0x01, 0x19, 0x54})
	types.RegisterSignature(types.KindUFSFilesystem, types.TypeNone, 1372, []byte{0x54, 0x19, 0x01, 0x00})
	types.RegisterSignature(types.KindUFSFilesystem, types.TypeNone, 8564, []byte{0x19, 0x01, 0x54, 0x19})
	types.RegisterSignature(types.KindUniversalDiskFormatImage, types.TypeNone, 32769, []byte("NSR02"))
	types.RegisterSignature(types.KindUniversalDiskFormatImage, types.TypeNone, 32769, []byte("NSR03"))
	types.RegisterSignature(types.KindVeeamBackup, types.TypeNone, 0, []byte("VBK "))
	types.RegisterSignature(types.KindVHDDiskImage, types.TypeNone, 0, []byte("conectix"))
	types.RegisterSignature(types.KindVHDDiskImage, types.TypeNone, 0, []byte("cxsparse"))
	types.RegisterSignature(types.KindVHDXDiskImage, types.TypeNone, 0, []byte("vhdxfile"))
	types.RegisterSignature(types.KindVirtualBoxDiskImage, types.TypeNone, 0, []byte("<<< Oracle VM VirtualBox Disk Image >>>\n"))
	types.RegisterSignature(types.KindVirtualBoxSavedState, types.TypeNone, 0, []byte("\x7fVBOXS"))
	types.RegisterSignature(types.KindVMwareDiskImage, types.TypeCopyOnWrite, 0, []byte("COWD"))
	types.RegisterSignature(types.KindVMwareDiskImage, types.TypeDescription, 0, []byte("# Disk D"))
	types.RegisterSignature(types.KindVMwareDiskImage, types.TypeKDMV, 0, []byte("KDMV"))
	types.RegisterSignature(types.KindVMwareDiskImage, types.TypeNone, 0, []byte("VMDK"))
	types.RegisterSignature(types.KindVMwareNVRAM, types.TypeNone, 0, []byte("MRVN"))
	types.RegisterSignature(types.KindVMwareNVRAM, types.TypeNone, 0, []byte("VMWARE NVRAM"))
	types.RegisterSignature(types.KindVMwareSnapshot, types.TypeNone, 0, []byte("VMSN"))
	types.RegisterSignature(types.KindVMwareSuspend, types.TypeNone, 0, []byte("VMSS"))
	types.RegisterSignature(types.KindVxFSFilesystem, types.TypeNone, 0, []byte{0xf5, 0xfc, 0x01, 0xa5})
	types.RegisterSignature(types.KindWiiUCompressedDiskImage, types.TypeNone, 0, []byte("WUX\x00"))
	types.RegisterSignature(types.KindWiiUDiskImage, types.TypeNone, 0, []byte("WUD\x00"))
	types.RegisterSignature(types.KindZFSFilesystem, types.TypeNone, 0, []byte{0x00, 0xba, 0xb1, 0x0c})
	types.RegisterSignature(types.KindZFSFilesystem, types.TypeNone, 0, []byte{0x0c, 0xb1, 0xba, 0x00})

	types.RegisterWeakSignature(types.KindApplePartitionMap, types.TypeNone, 512, []byte("ER"))
	types.RegisterWeakSignature(types.KindMasterBootRecord, types.TypeNone, 510, []byte{0x55, 0xaa})
	types.RegisterWeakSignature(types.KindMinixFilesystem, types.TypeNone, 1040, []byte{0x13, 0x7f})
	types.RegisterWeakSignature(types.KindMinixFilesystem, types.TypeNone, 1040, []byte{0x14, 0x7f})
	types.RegisterWeakSignature(types.KindMinixFilesystem, types.TypeNone, 1040, []byte{0x24, 0x78})
}
