package internal

import "github.com/coalaura/wtf/types"

func init() {
	types.RegisterSignature(types.KindAcronisTrueImage, types.TypeB4, 0, []byte{0xb4, 0x6e, 0x68, 0x44})
	types.RegisterSignature(types.KindAcronisTrueImage, types.TypeCE, 0, []byte{0xce, 0x24, 0xb9, 0xa2, 0x20, 0x00, 0x00, 0x00})
	types.RegisterSignature(types.KindAcronisTrueImage, types.TypeNone, 0, []byte{0xce, 0x24, 0xb5, 0xa0})
	types.RegisterSignature(types.KindAndroidSparseImage, types.TypeNone, 0, []byte{0x3a, 0xff, 0x26, 0xed})
	types.RegisterSignature(types.KindAPFSFilesystem, types.TypeNone, 32, []byte("NXSB"))
	types.RegisterSignature(types.KindAppleDiskImage, types.TypeNone, 0, []byte("cdsaencr"))
	types.RegisterSignature(types.KindAppleDiskImage, types.TypeNone, 0, []byte("encrcdsa"))
	types.RegisterSignature(types.KindAppleDiskImage, types.TypeNone, 0, []byte{0x78, 0x01, 0x73, 0x0d, 0x62, 0x62, 0x60})
	types.RegisterSignature(types.KindAppleISOHybridCDImage, types.TypeNone, 0, []byte{'E', 'R', 0x02, 0x00, 0x00})
	types.RegisterSignature(types.KindBcachefsFilesystem, types.TypeNone, 4096, []byte{0xc6, 0x85, 0x73, 0xf6, 0x4e, 0x1a, 0x45, 0xca, 0x82, 0x65, 0xf5, 0x7f, 0x48, 0xba, 0x6d, 0x81})
	types.RegisterSignature(types.KindBitLockerDiskEncryption, types.TypeNone, 3, []byte("-FVE-FS-"))
	types.RegisterSignature(types.KindBochsDiskImage, types.TypeNone, 0, []byte("Bochs Virtual HD Image"))
	types.RegisterSignature(types.KindBtrfsFilesystem, types.TypeNone, 0x10040, []byte("_BHRfS_M"))
	types.RegisterSignature(types.KindCramFS, types.TypeNone, 0, []byte{0x45, 0x3d, 0xcd, 0x28})
	types.RegisterSignature(types.KindExFATFilesystem, types.TypeNone, 3, []byte("EXFAT   "))
	types.RegisterSignature(types.KindF2FSFilesystem, types.TypeNone, 1024, []byte{0x10, 0x20, 0xf5, 0xf2})
	types.RegisterSignature(types.KindGUIDPartitionTable, types.TypeNone, 512, []byte("EFI PART"))
	types.RegisterSignature(types.KindHFSPlusFilesystem, types.TypeNone, 1024, []byte("H+"))
	types.RegisterSignature(types.KindHFSPlusFilesystem, types.TypeNone, 1024, []byte("HX"))
	types.RegisterSignature(types.KindISO9660Image, types.TypeNone, 0x8001, []byte("CD001"))
	types.RegisterSignature(types.KindJFFS2Filesystem, types.TypeNone, 0, []byte{0x85, 0x19})
	types.RegisterSignature(types.KindLUKSDiskEncryption, types.TypeNone, 0, []byte{'L', 'U', 'K', 'S', 0xba, 0xbe})
	types.RegisterSignature(types.KindMacriumReflectImage, types.TypeNone, 0, []byte("REFLECT "))
	types.RegisterSignature(types.KindNILFS2Filesystem, types.TypeNone, 1032, []byte{0x02, 0x09, 0x01, 0x12})
	types.RegisterSignature(types.KindNTFSFilesystem, types.TypeNone, 3, []byte("NTFS    "))
	types.RegisterSignature(types.KindParallelsDiskImage, types.TypeNone, 0, []byte("WithoutBorders"))
	types.RegisterSignature(types.KindPGPDiskImage, types.TypeNone, 0, []byte("PGPdMAIN"))
	types.RegisterSignature(types.KindQCOWDiskImage, types.TypeQCOW1, 0, []byte{'Q', 'F', 'I', 0xfb, 0x00, 0x00, 0x00, 0x01})
	types.RegisterSignature(types.KindQCOWDiskImage, types.TypeQCOW2, 0, []byte{'Q', 'F', 'I', 0xfb, 0x00, 0x00, 0x00, 0x02})
	types.RegisterSignature(types.KindQCOWDiskImage, types.TypeQCOW2, 0, []byte{'Q', 'F', 'I', 0xfb, 0x00, 0x00, 0x00, 0x03})
	types.RegisterSignature(types.KindQEMUQEDDiskImage, types.TypeNone, 0, []byte("QED\x00"))
	types.RegisterSignature(types.KindReiserFSFilesystem, types.TypeNone, 65588, []byte("ReIsEr2Fs"))
	types.RegisterSignature(types.KindReiserFSFilesystem, types.TypeNone, 65588, []byte("ReIsEr3Fs"))
	types.RegisterSignature(types.KindReiserFSFilesystem, types.TypeNone, 65588, []byte("ReIsEr4"))
	types.RegisterSignature(types.KindReiserFSFilesystem, types.TypeNone, 65588, []byte("ReIsErFs"))
	types.RegisterSignature(types.KindROMFS, types.TypeNone, 0, []byte("-rom1fs-"))
	types.RegisterSignature(types.KindRuntimeSoftwareImage, types.TypeNone, 0, []byte("RTS COM"))
	types.RegisterSignature(types.KindRuntimeSoftwareImage, types.TypeNone, 0, []byte{0x1a, 'R', 'T', 'S', ' ', 'C', 'O', 'M'})
	types.RegisterSignature(types.KindSteganosVirtualDrive, types.TypeNone, 0, []byte("ACv"))
	types.RegisterSignature(types.KindSymantecGhostImage, types.TypeNone, 0, []byte{0xfe, 0xef, 0x01, 0x01})
	types.RegisterSignature(types.KindSymantecGhostImage, types.TypeNone, 0, []byte{0xfe, 0xef, 0x02, 0x01})
	types.RegisterSignature(types.KindTeraByteImage, types.TypeNone, 0, []byte{0x00, 0x00, 0x00, 0x00, 0x14, 0x00, 0x00, 0x00})
	types.RegisterSignature(types.KindUBIFSFilesystem, types.TypeNone, 0, []byte{0x31, 0x18, 0x10, 0x06})
	types.RegisterSignature(types.KindUniversalDiskFormat, types.TypeNone, 32769, []byte("NSR02"))
	types.RegisterSignature(types.KindUniversalDiskFormat, types.TypeNone, 32769, []byte("NSR03"))
	types.RegisterSignature(types.KindVeeamBackup, types.TypeNone, 0, []byte("VBK "))
	types.RegisterSignature(types.KindVHDDiskImage, types.TypeNone, 0, []byte("conectix"))
	types.RegisterSignature(types.KindVHDDiskImage, types.TypeNone, 0, []byte("cxsparse"))
	types.RegisterSignature(types.KindVHDXDiskImage, types.TypeNone, 0, []byte("vhdxfile"))
	types.RegisterSignature(types.KindVirtualBoxDiskImage, types.TypeNone, 0, []byte("<<< Oracle VM VirtualBox Disk Image >>>\n"))
	types.RegisterSignature(types.KindVirtualBoxSavedState, types.TypeNone, 0, []byte("\x7fVBOXS"))
	types.RegisterSignature(types.KindVMwareDiskImage, types.TypeCOWD, 0, []byte("COWD"))
	types.RegisterSignature(types.KindVMwareDiskImage, types.TypeKDM, 0, []byte("KDMV"))
	types.RegisterSignature(types.KindVMwareDiskImage, types.TypeVMDK, 0, []byte("VMDK"))
	types.RegisterSignature(types.KindVMwareDiskImage, types.TypeVMDKDescription, 0, []byte("# Disk D"))
	types.RegisterSignature(types.KindVMwareNVRAM, types.TypeNone, 0, []byte("MRVN"))
	types.RegisterSignature(types.KindVMwareNVRAM, types.TypeNone, 0, []byte("VMWARE NVRAM"))
	types.RegisterSignature(types.KindVMwareSnapshot, types.TypeNone, 0, []byte("VMSN"))
	types.RegisterSignature(types.KindVMwareSuspend, types.TypeNone, 0, []byte("VMSS"))
	types.RegisterSignature(types.KindZFSFilesystem, types.TypeNone, 0, []byte{0x00, 0xba, 0xb1, 0x0c})
	types.RegisterSignature(types.KindZFSFilesystem, types.TypeNone, 0, []byte{0x0c, 0xb1, 0xba, 0x00})
}
