package internal

import "github.com/coalaura/wtf/types"

func init() {
	types.RegisterSignature(types.KindAmigaDiskImage, types.TypeNone, 0, []byte("DOS\x00"))
	types.RegisterSignature(types.KindAmigaDiskImage, types.TypeNone, 0, []byte("DOS\x01"))
	types.RegisterSignature(types.KindAmigaDiskImage, types.TypeNone, 0, []byte("DOS\x02"))
	types.RegisterSignature(types.KindAmigaDiskImage, types.TypeNone, 0, []byte("DOS\x03"))
	types.RegisterSignature(types.KindAmigaHardDiskImage, types.TypeNone, 0, []byte("RDSK"))
	types.RegisterSignature(types.KindAtari7800ROM, types.TypeNone, 1, []byte("ATARI7800"))
	types.RegisterSignature(types.KindAtariLynxROM, types.TypeNone, 0, []byte("LYNX"))
	types.RegisterSignature(types.KindCloneCDControl, types.TypeNone, 0, []byte("[CloneCD]"))
	types.RegisterSignature(types.KindCommodore64TapeImage, types.TypeNone, 0, []byte("C64 tape image file"))
	types.RegisterSignature(types.KindCommodore64TapeRAWImage, types.TypeNone, 0, []byte("C64-TAPE-RAW"))
	types.RegisterSignature(types.KindCompressedSquareWave, types.TypeNone, 0, []byte("Compressed Square Wave"))
	types.RegisterSignature(types.KindDolphinRVZ, types.TypeNone, 0, []byte("RVZ\x01"))
	types.RegisterSignature(types.KindFamicomDiskSystemROM, types.TypeNone, 0, []byte("FDS\x1a"))
	types.RegisterSignature(types.KindGodotPackage, types.TypeNone, 0, []byte("GDPC"))
	types.RegisterSignature(types.KindMAMECHDDiskImage, types.TypeNone, 0, []byte("MComprHD"))
	types.RegisterSignature(types.KindMicrosoftXbox360Profile, types.TypeNone, 0, []byte("CON "))
	types.RegisterSignature(types.KindMicrosoftXbox360Profile, types.TypeNone, 0, []byte("LIVE"))
	types.RegisterSignature(types.KindMicrosoftXbox360Profile, types.TypeNone, 0, []byte("PIRS"))
	types.RegisterSignature(types.KindMicrosoftXboxSave, types.TypeNone, 0, []byte("XBOX_SAVE"))
	types.RegisterSignature(types.KindMoPaQArchive, types.TypeNone, 0, []byte("MPQ\x1a"))
	types.RegisterSignature(types.KindMUGENAudio, types.TypeNone, 0, []byte("ElecbyteSnd\x00"))
	types.RegisterSignature(types.KindMUGENSprite, types.TypeNone, 0, []byte("ElecbyteSpr\x00"))
	types.RegisterSignature(types.KindNeoGeoPocketROM, types.TypeNone, 34, []byte("LICENSED BY SNK CORPORATION"))
	types.RegisterSignature(types.KindNintendoBCFNT, types.TypeNone, 0, []byte("CFFN"))
	types.RegisterSignature(types.KindNintendoBFLYT, types.TypeNone, 0, []byte("FLYT"))
	types.RegisterSignature(types.KindNintendoBRRES, types.TypeNone, 0, []byte("bres"))
	types.RegisterSignature(types.KindNintendoDSiROM, types.TypeNone, 0x180, []byte{0x24, 0xff, 0xae, 0x51, 0x69, 0x9a, 0xa2, 0x21})
	types.RegisterSignature(types.KindNintendoRARCArchive, types.TypeNone, 0, []byte("RARC"))
	types.RegisterSignature(types.KindNintendoSwitchNROExecutable, types.TypeNone, 16, []byte("NRO0"))
	types.RegisterSignature(types.KindNintendoSwitchNSOExecutable, types.TypeNone, 0, []byte("NSO0"))
	types.RegisterSignature(types.KindNintendoU8Archive, types.TypeNone, 0, []byte{0x55, 0xaa, 0x38, 0x2d})
	types.RegisterSignature(types.KindNintendoWiiUExecutable, types.TypeNone, 0, []byte("RPX\x00"))
	types.RegisterSignature(types.KindNintendoYay0Archive, types.TypeNone, 0, []byte("Yay0"))
	types.RegisterSignature(types.KindNintendoYaz0Archive, types.TypeNone, 0, []byte("Yaz0"))
	types.RegisterSignature(types.KindPico8Cartridge, types.TypeNone, 0, []byte("\x89p8\x00"))
	types.RegisterSignature(types.KindPlayStation1Executable, types.TypeNone, 0, []byte("PS-X EXE"))
	types.RegisterSignature(types.KindPlayStation2MemoryCard, types.TypeNone, 0, []byte("Sony PS2 Memory Card Format "))
	types.RegisterSignature(types.KindPlayStationExecutable, types.TypeNone, 0, []byte("SCE\x00"))
	types.RegisterSignature(types.KindPlayStationPortableExecutable, types.TypeNone, 0, []byte("\x00PBP"))
	types.RegisterSignature(types.KindRenPyArchive, types.TypeNone, 0, []byte("RPA-3.0 "))
	types.RegisterSignature(types.KindRPGMakerArchive, types.TypeNone, 0, []byte("RGSSAD\x00"))
	types.RegisterSignature(types.KindSegaCDImage, types.TypeNone, 0, []byte("SEGADISCSYSTEM"))
	types.RegisterSignature(types.KindSegaCDImage, types.TypeNone, 16, []byte("SEGADISCSYSTEM"))
	types.RegisterSignature(types.KindSegaDreamcastROM, types.TypeNone, 16, []byte("SEGA SEGAKATANA"))
	types.RegisterSignature(types.KindSegaMasterSystemROM, types.TypeNone, 0x1FF0, []byte("TMR SEGA"))
	types.RegisterSignature(types.KindSegaMasterSystemROM, types.TypeNone, 0x3FF0, []byte("TMR SEGA"))
	types.RegisterSignature(types.KindSegaMasterSystemROM, types.TypeNone, 0x7FF0, []byte("TMR SEGA"))
	types.RegisterSignature(types.KindSegaNaomiROM, types.TypeNone, 0, []byte("NAOMI"))
	types.RegisterSignature(types.KindSegaSaturnROM, types.TypeNone, 0, []byte("SEGA SEGA"))
	types.RegisterSignature(types.KindSourceEngineBSPMap, types.TypeNone, 0, []byte("VBSP"))
	types.RegisterSignature(types.KindUnityWebData, types.TypeNone, 0, []byte("UnityFS"))
	types.RegisterSignature(types.KindUnityWebData, types.TypeNone, 0, []byte("UnityRaw"))
	types.RegisterSignature(types.KindUnityWebData, types.TypeNone, 0, []byte("UnityWeb"))
	types.RegisterSignature(types.KindUnrealEnginePackage, types.TypeNone, 0, []byte{0xc1, 0x83, 0x2a, 0x9e})
	types.RegisterSignature(types.KindValvePak, types.TypeNone, 0, []byte{0x34, 0x12, 0xaa, 0x55})
	types.RegisterSignature(types.KindWarcraftIIIReplay, types.TypeNone, 0, []byte("Warcraft III recorded game\x1a\x00"))
	types.RegisterSignature(types.KindWiiUArchive, types.TypeNone, 0, []byte("WUA\x01"))
	types.RegisterSignature(types.KindXbox360Executable, types.TypeNone, 0, []byte("XEX2"))
	types.RegisterSignature(types.KindXboxExecutable, types.TypeNone, 0, []byte("XBEH"))
}
