package internal

import "github.com/coalaura/onda/types"

func init() {
	types.RegisterSignature(types.KindAOLARTImage, types.TypeNone, 0, []byte("JG\x03\x0e"))
	types.RegisterSignature(types.KindAOLARTImage, types.TypeNone, 0, []byte("JG\x04\x0e"))
	types.RegisterSignature(types.KindAppleTexture, types.TypeNone, 0, []byte("ATX "))
	types.RegisterSignature(types.KindARRIRAWImage, types.TypeNone, 0, []byte("ARRI"))
	types.RegisterSignature(types.KindASTCTexture, types.TypeNone, 0, []byte{0x13, 0xab, 0xa1, 0x5c})
	types.RegisterSignature(types.KindBlizzardTexture, types.TypeNone, 0, []byte("BLP1"))
	types.RegisterSignature(types.KindBlizzardTexture, types.TypeNone, 0, []byte("BLP2"))
	types.RegisterSignature(types.KindBMPImage, types.TypeNone, 0, []byte("BM"))
	types.RegisterSignature(types.KindBPGImage, types.TypeNone, 0, []byte{'B', 'P', 'G', 0xfb})
	types.RegisterSignature(types.KindBrotherEmbroidery, types.TypePEC, 0, []byte("#PEC0001"))
	types.RegisterSignature(types.KindBrotherEmbroidery, types.TypePES, 0, []byte("#PES0"))
	types.RegisterSignature(types.KindCALSImage, types.TypeNone, 0, []byte("srcdocid:"))
	types.RegisterSignature(types.KindCanonRAWImage, types.TypeHE, 0, []byte{'I', 'I', 0x1a, 0x00, 0x00, 0x00, 'H', 'E'})
	types.RegisterSignature(types.KindChromaGraphBitmap, types.TypeNone, 0, []byte("PICT\x00\x08"))
	types.RegisterSignature(types.KindCineonImage, types.TypeNone, 0, []byte{0x80, 0x2a, 0x5f, 0xd7})
	types.RegisterSignature(types.KindCorelBinaryMetafile, types.TypeNone, 0, []byte("CMX1"))
	types.RegisterSignature(types.KindCorelPhotoPaintImage, types.TypeNone, 0, []byte("CPTFILE"))
	types.RegisterSignature(types.KindDDSImage, types.TypeNone, 0, []byte("DDS "))
	types.RegisterSignature(types.KindDeluxePaintAnimation, types.TypeNone, 0, []byte("LPF \x00\x01"))
	types.RegisterSignature(types.KindDesignTools2D, types.TypeNone, 0, []byte("dt2ddtd"))
	types.RegisterSignature(types.KindDesignTools2D, types.TypeNone, 0, []byte{0x07, 0x64, 0x74, 0x32, 0x64, 0x64, 0x74, 0x64})
	types.RegisterSignature(types.KindDPXImage, types.TypeBigEndian, 0, []byte("SDPX"))
	types.RegisterSignature(types.KindDPXImage, types.TypeLittleEndian, 0, []byte("XPDS"))
	types.RegisterSignature(types.KindEasyStreetDraw, types.TypeNone, 0, []byte{0x7e, 0x45, 0x53, 0x44, 0x77, 0xf6, 0x85, 0x3e, 0xbf, 0x6a, 0xd2, 0x11, 0x45, 0x61, 0x73, 0x79, 0x20, 0x53, 0x74, 0x72, 0x65, 0x65, 0x74, 0x20, 0x44, 0x72, 0x61, 0x77})
	types.RegisterSignature(types.KindFarbfeldImage, types.TypeNone, 0, []byte("farbfeld"))
	types.RegisterSignature(types.KindFLIFImage, types.TypeNone, 0, []byte("FLIF"))
	types.RegisterSignature(types.KindFujifilmRAWImage, types.TypeNone, 0, []byte("FUJIFILMCCD-RAW "))
	types.RegisterSignature(types.KindFuzzyBitmap, types.TypeNone, 0, []byte("%bitmap"))
	types.RegisterSignature(types.KindGEMRaster, types.TypeNone, 0, []byte{0xeb, 0x3c, 0x90, 0x2a})
	types.RegisterSignature(types.KindGIFImage, types.TypeGIF87a, 0, []byte("GIF87a"))
	types.RegisterSignature(types.KindGIFImage, types.TypeGIF89a, 0, []byte("GIF89a"))
	types.RegisterSignature(types.KindGIMPBrush, types.TypeNone, 20, []byte("GIMP Brush\n"))
	types.RegisterSignature(types.KindGIMPPattern, types.TypeNone, 0, []byte("GPAT"))
	types.RegisterSignature(types.KindGIMPPattern, types.TypeNone, 24, []byte("GIMP Pattern\n"))
	types.RegisterSignature(types.KindGIMPXCFImage, types.TypeNone, 0, []byte("gimp xcf "))
	types.RegisterSignature(types.KindGLTFBinary, types.TypeNone, 0, []byte("glTF"))
	types.RegisterSignature(types.KindHuskygramPoem, types.TypeNone, 0, []byte{0x7c, 0x4b, 0xc3, 0x74, 0xe1, 0xc8, 0x53, 0xa4, 0x79, 0xb9, 0x01, 0x1d, 0xfc, 0x4f, 0xdd, 0x13})
	types.RegisterSignature(types.KindICCProfile, types.TypeNone, 36, []byte("acsp"))
	types.RegisterSignature(types.KindICNSIcon, types.TypeNone, 0, []byte("icns"))
	types.RegisterSignature(types.KindICOCURImage, types.TypeWindowsCursor, 0, []byte{0x00, 0x00, 0x02, 0x00})
	types.RegisterSignature(types.KindICOCURImage, types.TypeWindowsIcon, 0, []byte{0x00, 0x00, 0x01, 0x00})
	types.RegisterSignature(types.KindIFFContainer, types.TypeCAT, 0, []byte("CAT "))
	types.RegisterSignature(types.KindIFFContainer, types.TypeLIST, 0, []byte("LIST"))
	types.RegisterSignature(types.KindImgSoftwareBitmap, types.TypeNone, 0, []byte("SCMI"))
	types.RegisterSignature(types.KindJBIG2Image, types.TypeNone, 0, []byte{0x97, 'J', 'B', '2', '\r', '\n', 0x1a, '\n'})
	types.RegisterSignature(types.KindJNGImage, types.TypeNone, 0, []byte{0x8b, 'J', 'N', 'G', 0x0d, 0x0a, 0x1a, 0x0a})
	types.RegisterSignature(types.KindJPEG2000Image, types.TypeCodestream, 0, []byte{0xff, 0x4f, 0xff, 0x51})
	types.RegisterSignature(types.KindJPEG2000Image, types.TypeNone, 0, []byte{0x00, 0x00, 0x00, 0x0c, 'j', 'P', ' ', ' ', 0x0d, 0x0a, 0x87, 0x0a})
	types.RegisterSignature(types.KindJPEGImage, types.TypeNone, 0, []byte{0xff, 0xd8, 0xff})
	types.RegisterSignature(types.KindJPEGLSImage, types.TypeNone, 0, []byte{0xff, 0xd8, 0xff, 0xf7})
	types.RegisterSignature(types.KindJPEGXLImage, types.TypeCodestream, 0, []byte{0xff, 0x0a})
	types.RegisterSignature(types.KindJPEGXLImage, types.TypeContainer, 0, []byte{0x00, 0x00, 0x00, 0x0c, 'J', 'X', 'L', ' ', 0x0d, 0x0a, 0x87, 0x0a})
	types.RegisterSignature(types.KindJPEGXRImage, types.TypeBigEndian, 0, []byte{'M', 'M', 0x01, 0xbc})
	types.RegisterSignature(types.KindJPEGXRImage, types.TypeLittleEndian, 0, []byte{'I', 'I', 0xbc, 0x01})
	types.RegisterSignature(types.KindKTXTexture, types.TypeKTX, 0, []byte{0xab, 'K', 'T', 'X', ' ', '1', '1', 0xbb, 0x0d, 0x0a, 0x1a, 0x0a})
	types.RegisterSignature(types.KindKTXTexture, types.TypeKTX2, 0, []byte{0xab, 'K', 'T', 'X', ' ', '2', '0', 0xbb, 0x0d, 0x0a, 0x1a, 0x0a})
	types.RegisterSignature(types.KindLytroLightField, types.TypeNone, 0, []byte("\x89LFP\x0d\x0a\x1a\x0a"))
	types.RegisterSignature(types.KindMagicaVoxel, types.TypeNone, 0, []byte("VOX "))
	types.RegisterSignature(types.KindMetafileImage, types.TypeWindowsMetafileWMF, 0, []byte{0xd7, 0xcd, 0xc6, 0x9a})
	types.RegisterSignature(types.KindMicrografxDrawing, types.TypeNone, 0, []byte{0x01, 0xff, 0x02, 0x04, 0x03, 0x02})
	types.RegisterSignature(types.KindMinoltaRAWImage, types.TypeNone, 0, []byte("\x00MRM"))
	types.RegisterSignature(types.KindMNGImage, types.TypeNone, 0, []byte{0x8a, 'M', 'N', 'G', 0x0d, 0x0a, 0x1a, 0x0a})
	types.RegisterSignature(types.KindMonochromePictureTIFF, types.TypeNone, 0, []byte{0x0c, 0xed})
	types.RegisterSignature(types.KindNIfTIMedicalImage, types.TypeNone, 344, []byte("n+1\x00"))
	types.RegisterSignature(types.KindNIfTIMedicalImage, types.TypeNone, 344, []byte("ni1\x00"))
	types.RegisterSignature(types.KindNintendoTPL, types.TypeNone, 0, []byte{0x00, 0x20, 0xaf, 0x30})
	types.RegisterSignature(types.KindNOAARasterChart, types.TypeNone, 0, []byte("!\r\nCRR/This elec"))
	types.RegisterSignature(types.KindOpenEXRImage, types.TypeNone, 0, []byte{0x76, 0x2f, 0x31, 0x01})
	types.RegisterSignature(types.KindPaintShopProImage, types.TypeNone, 0, []byte("Paint Shop Pro Image File\n\x1a\x00"))
	types.RegisterSignature(types.KindPaintShopProImage, types.TypeNone, 0, []byte("~BK\x00"))
	types.RegisterSignature(types.KindPAXBitmap, types.TypeNone, 0, []byte("PAX"))
	types.RegisterSignature(types.KindPCXDCXBitmap, types.TypeNone, 0, []byte{0xb1, 0x68, 0xde, 0x3a})
	types.RegisterSignature(types.KindPfaffEmbroidery, types.TypeNone, 0, []byte{0x32, 0x03, 0x10, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x00, 0x00, 0x00, 0xff, 0x00})
	types.RegisterSignature(types.KindPGFImage, types.TypeNone, 0, []byte("PGF"))
	types.RegisterSignature(types.KindPhotoshopCustomShape, types.TypeNone, 0, []byte("cush\x00\x00\x00\x02"))
	types.RegisterSignature(types.KindPhotoshopDocument, types.TypePSB, 0, []byte("8BPB"))
	types.RegisterSignature(types.KindPhotoshopDocument, types.TypePSD, 0, []byte("8BPS"))
	types.RegisterSignature(types.KindPNGImage, types.TypeNone, 0, []byte{137, 'P', 'N', 'G', 13, 10, 26, 10})
	types.RegisterSignature(types.KindPVRTexture, types.TypeNone, 0, []byte("PVR\x03"))
	types.RegisterSignature(types.KindQimageFilter, types.TypeNone, 0, []byte("v2003.10"))
	types.RegisterSignature(types.KindQOIImage, types.TypeNone, 0, []byte("qoif"))
	types.RegisterSignature(types.KindRadianceHDRImage, types.TypeNone, 0, []byte("#?RADIANCE"))
	types.RegisterSignature(types.KindRadianceHDRImage, types.TypeNone, 0, []byte("#?RGBE"))
	types.RegisterSignature(types.KindREDRAWImage, types.TypeNone, 4, []byte("RED2"))
	types.RegisterSignature(types.KindSGIImage, types.TypeNone, 0, []byte{0x01, 0xda})
	types.RegisterSignature(types.KindShareazaThumbnail, types.TypeNone, 0, []byte("RAZATDB1"))
	types.RegisterSignature(types.KindShowPartnerGraphics, types.TypeNone, 0, []byte("GX2"))
	types.RegisterSignature(types.KindSigmaRAWImage, types.TypeNone, 0, []byte("FOVb"))
	types.RegisterSignature(types.KindSunRasterImage, types.TypeNone, 0, []byte{0x59, 0xa6, 0x6a, 0x95})
	types.RegisterSignature(types.KindTajimaEmbroidery, types.TypeNone, 0, []byte("LA:"))
	types.RegisterSignature(types.KindTIFFImage, types.TypeBigTIFF, 0, []byte{'M', 'M', 0x00, '+'})
	types.RegisterSignature(types.KindUniversalSceneDescription, types.TypeNone, 0, []byte("PXR-USDC"))
	types.RegisterSignature(types.KindValveTextureFormat, types.TypeNone, 0, []byte("VTF\x00"))
	types.RegisterSignature(types.KindWindowsThumbnailCache, types.TypeIMMM, 0, []byte("IMMM\x15\x00\x00\x00"))
	types.RegisterSignature(types.KindWindowsThumbnailCache, types.TypeNone, 0, []byte("CMMM\x15\x00\x00\x00"))
	types.RegisterSignature(types.KindWordPerfectGraphics, types.TypeNone, 0, []byte("\xffWPC"))
	types.RegisterSignature(types.KindXBMImage, types.TypeNone, 0, []byte("#define "))
	types.RegisterSignature(types.KindXPMImage, types.TypeNone, 0, []byte("/* XPM */"))
	types.RegisterSignature(types.KindZoomBrowserIndex, types.TypeNone, 0, []byte("zbex"))

	types.RegisterMaskedSignature(types.KindDjVuDocument, types.TypeNone, 0, []byte("AT&TFORM\x00\x00\x00\x00DJVI"), []byte{0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0, 0, 0, 0, 0xff, 0xff, 0xff, 0xff})
	types.RegisterMaskedSignature(types.KindDjVuDocument, types.TypeNone, 0, []byte("AT&TFORM\x00\x00\x00\x00DJVM"), []byte{0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0, 0, 0, 0, 0xff, 0xff, 0xff, 0xff})
	types.RegisterMaskedSignature(types.KindDjVuDocument, types.TypeNone, 0, []byte("AT&TFORM\x00\x00\x00\x00DJVU"), []byte{0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0, 0, 0, 0, 0xff, 0xff, 0xff, 0xff})
	types.RegisterMaskedSignature(types.KindDjVuDocument, types.TypeNone, 0, []byte("AT&TFORM\x00\x00\x00\x00THUM"), []byte{0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0, 0, 0, 0, 0xff, 0xff, 0xff, 0xff})
	types.RegisterMaskedSignature(types.KindDjVuDocument, types.TypeNone, 0, []byte("FORM\x00\x00\x00\x00DJVI"), []byte{0xff, 0xff, 0xff, 0xff, 0, 0, 0, 0, 0xff, 0xff, 0xff, 0xff})
	types.RegisterMaskedSignature(types.KindDjVuDocument, types.TypeNone, 0, []byte("FORM\x00\x00\x00\x00DJVM"), []byte{0xff, 0xff, 0xff, 0xff, 0, 0, 0, 0, 0xff, 0xff, 0xff, 0xff})
	types.RegisterMaskedSignature(types.KindDjVuDocument, types.TypeNone, 0, []byte("FORM\x00\x00\x00\x00DJVU"), []byte{0xff, 0xff, 0xff, 0xff, 0, 0, 0, 0, 0xff, 0xff, 0xff, 0xff})
	types.RegisterMaskedSignature(types.KindDjVuDocument, types.TypeNone, 0, []byte("FORM\x00\x00\x00\x00THUM"), []byte{0xff, 0xff, 0xff, 0xff, 0, 0, 0, 0, 0xff, 0xff, 0xff, 0xff})
	types.RegisterMaskedSignature(types.KindIFFContainer, types.TypeILBMImage, 0, []byte("FORM\x00\x00\x00\x00ILBM"), []byte{0xff, 0xff, 0xff, 0xff, 0x00, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff})
	types.RegisterMaskedSignature(types.KindMetafileImage, types.TypeEnhancedMetafileEMF, 0, []byte{0x01, 0x00, 0x00, 0x00, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x20, 0x45, 0x4d, 0x46}, []byte{0xff, 0xff, 0xff, 0xff, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0xff, 0xff, 0xff, 0xff})
	types.RegisterMaskedSignature(types.KindRIFFContainer, types.TypeRIFFPalette, 0, []byte("RIFF\x00\x00\x00\x00PAL "), []byte{0xff, 0xff, 0xff, 0xff, 0x00, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff})
	types.RegisterMaskedSignature(types.KindRIFFContainer, types.TypeWebPImage, 0, []byte("RIFF\x00\x00\x00\x00WEBP"), []byte{0xff, 0xff, 0xff, 0xff, 0x00, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff})
}
