package internal

import "github.com/coalaura/wtf/types"

func init() {
	types.RegisterSignature(types.Kind1PasswordCloudKeychain, types.TypeNone, 0, []byte("opdata01"))
	types.RegisterSignature(types.KindAmigaHunkExecutable, types.TypeNone, 0, []byte{0x00, 0x00, 0x03, 0xf3})
	types.RegisterSignature(types.KindAmigaIcon, types.TypeNone, 0, []byte{0xe3, 0x10, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00})
	types.RegisterSignature(types.KindAndroidART, types.TypeNone, 0, []byte("art\n"))
	types.RegisterSignature(types.KindAndroidBackup, types.TypeNone, 0, []byte("ANDROID BACKUP\n"))
	types.RegisterSignature(types.KindAndroidBinaryXML, types.TypeNone, 0, []byte{0x03, 0x00, 0x08, 0x00})
	types.RegisterSignature(types.KindAndroidBootImage, types.TypeNone, 0, []byte("ANDROID!"))
	types.RegisterSignature(types.KindAndroidCompiledResources, types.TypeNone, 0, []byte{0x02, 0x00, 0x0c, 0x00})
	types.RegisterSignature(types.KindAndroidOAT, types.TypeNone, 0, []byte("oat\n"))
	types.RegisterSignature(types.KindAndroidODEX, types.TypeNone, 0, []byte("dey\n"))
	types.RegisterSignature(types.KindAndroidVDEX, types.TypeNone, 0, []byte("vdex"))
	types.RegisterSignature(types.KindAppleBillOfMaterials, types.TypeNone, 0, []byte("BOMStore"))
	types.RegisterSignature(types.KindAppleBinaryCrashReport, types.TypeNone, 0, []byte("CRAS"))
	types.RegisterSignature(types.KindAppleBinaryPropertyList, types.TypeNone, 0, []byte("bplist"))
	types.RegisterSignature(types.KindAppleDoubleArchive, types.TypeNone, 0, []byte{0x00, 0x05, 0x16, 0x07})
	types.RegisterSignature(types.KindAppleKeychain, types.TypeNone, 0, []byte("kych"))
	types.RegisterSignature(types.KindAppleSingleArchive, types.TypeNone, 0, []byte{0x00, 0x05, 0x16, 0x00})
	types.RegisterSignature(types.KindAppleSystemLog, types.TypeNone, 0, []byte("ASL "))
	types.RegisterSignature(types.KindBinHexArchive, types.TypeNone, 11, []byte("must be converted with BinHex 4.0"))
	types.RegisterSignature(types.KindBitcoinBlock, types.TypeNone, 0, []byte{0xf9, 0xbe, 0xb4, 0xd9})
	types.RegisterSignature(types.KindBlackBerryBackup, types.TypeNone, 0, []byte("Inter@ctive Page"))
	types.RegisterSignature(types.KindBlenderProject, types.TypeNone, 0, []byte("BLENDER"))
	types.RegisterSignature(types.KindBouncyCastleKeystore, types.TypeNone, 0, []byte("UBER"))
	types.RegisterSignature(types.KindChromiumPatch, types.TypeNone, 0, []byte("CrOD"))
	types.RegisterSignature(types.KindCompiledTerminfo, types.TypeNone, 0, []byte{0x1a, 0x01})
	types.RegisterSignature(types.KindCOMPlusCatalog, types.TypeNone, 0, []byte("COM+"))
	types.RegisterSignature(types.KindCRXBrowserExtension, types.TypeNone, 0, []byte("Cr24"))
	types.RegisterSignature(types.KindCRXBrowserExtension, types.TypeVersion2, 0, []byte("Cr24\x02\x00\x00\x00"))
	types.RegisterSignature(types.KindCRXBrowserExtension, types.TypeVersion3, 0, []byte("Cr24\x03\x00\x00\x00"))
	types.RegisterSignature(types.KindDalvikExecutable, types.TypeVersion035, 0, []byte("dex\n035\x00"))
	types.RegisterSignature(types.KindDalvikExecutable, types.TypeVersion036, 0, []byte("dex\n036\x00"))
	types.RegisterSignature(types.KindDalvikExecutable, types.TypeVersion037, 0, []byte("dex\n037\x00"))
	types.RegisterSignature(types.KindDalvikExecutable, types.TypeVersion038, 0, []byte("dex\n038\x00"))
	types.RegisterSignature(types.KindDalvikExecutable, types.TypeVersion039, 0, []byte("dex\n039\x00"))
	types.RegisterSignature(types.KindDalvikExecutable, types.TypeVersion040, 0, []byte("dex\n040\x00"))
	types.RegisterSignature(types.KindDalvikExecutable, types.TypeVersion041, 0, []byte("dex\n041\x00"))
	types.RegisterSignature(types.KindDialUpNetworking, types.TypeNone, 0, []byte("[Phone]"))
	types.RegisterSignature(types.KindFlightSimulatorConfig, types.TypeNone, 0, []byte("[fltsim."))
	types.RegisterSignature(types.KindGameBoyAdvanceROM, types.TypeNone, 0x04, []byte{0x24, 0xff, 0xae, 0x51, 0x69, 0x9a, 0xa2, 0x21})
	types.RegisterSignature(types.KindGameBoyROM, types.TypeNone, 0x104, []byte{0xce, 0xed, 0x66, 0x66, 0xcc, 0x0d, 0x00, 0x0b})
	types.RegisterSignature(types.KindGameCubeROM, types.TypeNone, 0x1c, []byte{0xc2, 0x33, 0x9f, 0x3d})
	types.RegisterSignature(types.KindGitIndex, types.TypeNone, 0, []byte("DIRC"))
	types.RegisterSignature(types.KindGitPack, types.TypeNone, 0, []byte("PACK"))
	types.RegisterSignature(types.KindGlibcLocale, types.TypeNone, 0, []byte{0xde, 0xc0, 0x26, 0xe8})
	types.RegisterSignature(types.KindGNOMEKeyring, types.TypeNone, 0, []byte("GnomeKeyring\n\r\x00\n"))
	types.RegisterSignature(types.KindGnuPGKeybox, types.TypeNone, 0, []byte("KBXf"))
	types.RegisterSignature(types.KindGoogleChromeDictionary, types.TypeNone, 0, []byte("BDic"))
	types.RegisterSignature(types.KindInnoSetupLog, types.TypeNone, 0, []byte("Inno Set"))
	types.RegisterSignature(types.KindInstallShieldScript, types.TypeNone, 0, []byte{0xb8, 0xc9, 0x0c, 0x00})
	types.RegisterSignature(types.KindJavaCryptographyExtensionKeyStore, types.TypeNone, 0, []byte{0xce, 0xce, 0xce, 0xce})
	types.RegisterSignature(types.KindJavaKeyStore, types.TypeNone, 0, []byte{0xfe, 0xed, 0xfe, 0xed})
	types.RegisterSignature(types.KindJavaModule, types.TypeNone, 0, []byte("JMOD"))
	types.RegisterSignature(types.KindJavaSerialization, types.TypeNone, 0, []byte{0xac, 0xed, 0x00, 0x05})
	types.RegisterSignature(types.KindKDEKWallet, types.TypeNone, 0, []byte("KWALLET\n\r\x00\r\n"))
	types.RegisterSignature(types.KindKeyboardDriver, types.TypeNone, 0, []byte{0xff, 0x4b, 0x45, 0x59, 0x42, 0x20, 0x20, 0x20})
	types.RegisterSignature(types.KindLinuxKernelImage, types.TypeNone, 514, []byte("HdrS"))
	types.RegisterSignature(types.KindLLVMBitcode, types.TypeNone, 0, []byte{'B', 'C', 0xc0, 0xde})
	types.RegisterSignature(types.KindLLVMBitcode, types.TypeWrapper, 0, []byte{0xde, 0xc0, 0x17, 0x0b})
	types.RegisterSignature(types.KindLuaBytecode, types.TypeNone, 0, []byte{0x1b, 'L', 'u', 'a'})
	types.RegisterSignature(types.KindLVM2PhysicalVolume, types.TypeNone, 512, []byte("LABELONE"))
	types.RegisterSignature(types.KindMacBinaryArchive, types.TypeNone, 102, []byte("mBIN"))
	types.RegisterSignature(types.KindMacOSAlias, types.TypeNone, 0, []byte{0x62, 0x6f, 0x6f, 0x6b, 0x00, 0x00, 0x00, 0x00, 0x6d, 0x61, 0x72, 0x6b, 0x00, 0x00, 0x00, 0x00})
	types.RegisterSignature(types.KindMacOSXCodeSignature, types.TypeNone, 0, []byte{0xfa, 0xde, 0x0c, 0x02})
	types.RegisterSignature(types.KindMacOSXCodeSignature, types.TypeNone, 0, []byte{0xfa, 0xde, 0x0c, 0x05})
	types.RegisterSignature(types.KindMicrosoftExchangeConfig, types.TypeNone, 0, []byte("[General"))
	types.RegisterSignature(types.KindMicrosoftProgramDatabase, types.TypeNone, 0, []byte("Microsoft C/C++ MSF 7.00\r\n\x1aDS\x00\x00\x00"))
	types.RegisterSignature(types.KindMilestonesProject, types.TypeNone, 0, []byte("MILES"))
	types.RegisterSignature(types.KindMilestonesProject, types.TypeNone, 0, []byte("MV214"))
	types.RegisterSignature(types.KindMilestonesProject, types.TypeNone, 0, []byte("MV2C"))
	types.RegisterSignature(types.KindNAVQuarantinedVirus, types.TypeNone, 0, []byte{0xcd, 0x20, 0xaa, 0xaa, 0x02, 0x00, 0x00, 0x00})
	types.RegisterSignature(types.KindNESROM, types.TypeNone, 0, []byte{'N', 'E', 'S', 0x1a})
	types.RegisterSignature(types.KindNintendo3DSROM, types.TypeNone, 0x100, []byte("NCSD"))
	types.RegisterSignature(types.KindNintendo64ROM, types.TypeBigEndian, 0, []byte{0x80, 0x37, 0x12, 0x40})
	types.RegisterSignature(types.KindNintendo64ROM, types.TypeByteSwapped, 0, []byte{0x37, 0x80, 0x40, 0x12})
	types.RegisterSignature(types.KindNintendo64ROM, types.TypeLittleEndian, 0, []byte{0x40, 0x12, 0x37, 0x80})
	types.RegisterSignature(types.KindNintendoDSROM, types.TypeNone, 0xc0, []byte{0x24, 0xff, 0xae, 0x51, 0x69, 0x9a, 0xa2, 0x21})
	types.RegisterSignature(types.KindNintendoSwitchPackage, types.TypeNone, 0, []byte("PFS0"))
	types.RegisterSignature(types.KindNintendoSwitchROM, types.TypeNone, 0x100, []byte("HEAD"))
	types.RegisterSignature(types.KindNokiaPhoneBackup, types.TypeNone, 0, []byte{0xcc, 0x52, 0x33, 0xfc, 0xe9, 0x2c, 0x18, 0x48, 0xaf, 0xe3, 0x36, 0x30, 0x1a, 0x39, 0x40, 0x06})
	types.RegisterSignature(types.KindNovellLANalyzerCapture, types.TypeNone, 0, []byte{0x01, 0x10})
	types.RegisterSignature(types.KindNVIDIASceneGraph, types.TypeNone, 0, []byte("#NBF"))
	types.RegisterSignature(types.KindOpenSSHPrivateKey, types.TypeNone, 0, []byte("openssh-key-v1\x00"))
	types.RegisterSignature(types.KindOpenTypeFont, types.TypeNone, 0, []byte("OTTO\x00"))
	types.RegisterSignature(types.KindPacketSnifferXCP, types.TypeNone, 0, []byte("XCP\x00"))
	types.RegisterSignature(types.KindPathWayMap, types.TypeNone, 60, []byte("tBMPKnWr"))
	types.RegisterSignature(types.KindPCAPCapture, types.TypeBigEndian, 0, []byte{0xa1, 0xb2, 0xc3, 0xd4})
	types.RegisterSignature(types.KindPCAPCapture, types.TypeBigEndian, 0, []byte{0xa1, 0xb2, 0xcd, 0x34})
	types.RegisterSignature(types.KindPCAPCapture, types.TypeLittleEndian, 0, []byte{0x34, 0xcd, 0xb2, 0xa1})
	types.RegisterSignature(types.KindPCAPCapture, types.TypeLittleEndian, 0, []byte{0xd4, 0xc3, 0xb2, 0xa1})
	types.RegisterSignature(types.KindPCAPCapture, types.TypeNanosecondBigEndian, 0, []byte{0xa1, 0xb2, 0x3c, 0x4d})
	types.RegisterSignature(types.KindPCAPCapture, types.TypeNanosecondLittleEndian, 0, []byte{0x4d, 0x3c, 0xb2, 0xa1})
	types.RegisterSignature(types.KindPEMCertificate, types.TypeNone, 0, []byte("-----BEGIN CERTIFICATE-----"))
	types.RegisterSignature(types.KindPEMPrivateKey, types.TypeDSA, 0, []byte("-----BEGIN DSA PRIVATE KEY-----"))
	types.RegisterSignature(types.KindPEMPrivateKey, types.TypeEC, 0, []byte("-----BEGIN EC PRIVATE KEY-----"))
	types.RegisterSignature(types.KindPEMPrivateKey, types.TypeNone, 0, []byte("-----BEGIN OPENSSH PRIVATE KEY-----"))
	types.RegisterSignature(types.KindPEMPrivateKey, types.TypeNone, 0, []byte("-----BEGIN PRIVATE KEY-----"))
	types.RegisterSignature(types.KindPEMPrivateKey, types.TypeRSA, 0, []byte("-----BEGIN RSA PRIVATE KEY-----"))
	types.RegisterSignature(types.KindPestPatrolData, types.TypeNone, 0, []byte("PEST"))
	types.RegisterSignature(types.KindPlayStationPortableISO, types.TypeNone, 0, []byte("CISO"))
	types.RegisterSignature(types.KindPowerBASICDebugger, types.TypeNone, 0, []byte("szez"))
	types.RegisterSignature(types.KindPuttyPrivateKey, types.TypeNone, 0, []byte("PuTTY-User-Key-File-"))
	types.RegisterSignature(types.KindQuickBooksBackup, types.TypeNone, 0, []byte{0x45, 0x86, 0x00, 0x00, 0x06, 0x00})
	types.RegisterSignature(types.KindSegaMegaDriveROM, types.TypeNone, 0x100, []byte("SEGA"))
	types.RegisterSignature(types.KindShebangScript, types.TypeNone, 0, []byte("#!"))
	types.RegisterSignature(types.KindShockwaveFlash, types.TypeLZMACompressed, 0, []byte("ZWS"))
	types.RegisterSignature(types.KindShockwaveFlash, types.TypeUncompressed, 0, []byte("FWS"))
	types.RegisterSignature(types.KindShockwaveFlash, types.TypeZlibCompressed, 0, []byte("CWS"))
	types.RegisterSignature(types.KindSpeedtouchFirmware, types.TypeNone, 0, []byte("BLI223"))
	types.RegisterSignature(types.KindSSHPublicKey, types.TypeNone, 0, []byte("ecdsa-sha2-nistp256 "))
	types.RegisterSignature(types.KindSSHPublicKey, types.TypeNone, 0, []byte("ssh-ed25519 "))
	types.RegisterSignature(types.KindSSHPublicKey, types.TypeNone, 0, []byte("ssh-rsa "))
	types.RegisterSignature(types.KindStorageCraftBackup, types.TypeNone, 0, []byte("SPFI\x00"))
	types.RegisterSignature(types.KindSymantecWiseInstallerLog, types.TypeNone, 0, []byte("***  Ins"))
	types.RegisterSignature(types.KindSymbianExecutable, types.TypeNone, 16, []byte("EPOC"))
	types.RegisterSignature(types.KindSymbianInstallationFormat, types.TypeNone, 0, []byte{0x1a, 0x45, 0x11, 0x10})
	types.RegisterSignature(types.KindSymbianInstallationFormat, types.TypeNone, 0, []byte{0x7a, 0x1a, 0x20, 0x10})
	types.RegisterSignature(types.KindSystemdJournal, types.TypeNone, 0, []byte("LPKSHHRH"))
	types.RegisterSignature(types.KindTargetExpress, types.TypeNone, 0, []byte("MCW Technogolies"))
	types.RegisterSignature(types.KindTomTomTrafficData, types.TypeNone, 0, []byte("NAVTRAFF"))
	types.RegisterSignature(types.KindUBootImage, types.TypeNone, 0, []byte{0x27, 0x05, 0x19, 0x56})
	types.RegisterSignature(types.KindUnicodeExtensions, types.TypeNone, 0, []byte("UCEX"))
	types.RegisterSignature(types.KindVBScriptEncoded, types.TypeNone, 0, []byte("#@~^"))
	types.RegisterSignature(types.KindVisualCWorkbenchInfo, types.TypeNone, 0, []byte("[MSVC"))
	types.RegisterSignature(types.KindVisualStudioSolution, types.TypeNone, 0, []byte("Microsoft Visual"))
	types.RegisterSignature(types.KindVMapSourceWaypoint, types.TypeNone, 0, []byte("MsRcf"))
	types.RegisterSignature(types.KindVulkanSPIRV, types.TypeBigEndian, 0, []byte{0x07, 0x23, 0x02, 0x03})
	types.RegisterSignature(types.KindVulkanSPIRV, types.TypeLittleEndian, 0, []byte{0x03, 0x02, 0x23, 0x07})
	types.RegisterSignature(types.KindWebAssemblyModule, types.TypeASCII, 0, []byte("(module "))
	types.RegisterSignature(types.KindWebAssemblyModule, types.TypeASCII, 0, []byte("(module\n"))
	types.RegisterSignature(types.KindWebAssemblyModule, types.TypeNone, 0, []byte{0x00, 0x61, 0x73, 0x6d})
	types.RegisterSignature(types.KindWiiBackupFileSystem, types.TypeNone, 0, []byte("WBFS"))
	types.RegisterSignature(types.KindWiiROM, types.TypeNone, 0x18, []byte{0x5d, 0x1c, 0x9e, 0xa3})
	types.RegisterSignature(types.KindWin95Password, types.TypeNone, 0, []byte{0xb0, 0x4d, 0x46, 0x43})
	types.RegisterSignature(types.KindWin9xPassword, types.TypeNone, 0, []byte{0xe3, 0x82, 0x85, 0x96})
	types.RegisterSignature(types.KindWin9xPrinterSpool, types.TypeNone, 0, []byte("fI\x00\x00"))
	types.RegisterSignature(types.KindWin9xPrinterSpool, types.TypeNone, 0, []byte("gI\x00\x00"))
	types.RegisterSignature(types.KindWin9xPrinterSpool, types.TypeNone, 0, []byte("hI\x00\x00"))
	types.RegisterSignature(types.KindWin9xPrinterSpool, types.TypeNone, 0, []byte("KI\x00\x00"))
	types.RegisterSignature(types.KindWin9xRegistryHive, types.TypeNone, 0, []byte("CREG"))
	types.RegisterSignature(types.KindWindowsCalendar, types.TypeNone, 0, []byte{0xb5, 0xa2, 0xb0, 0xb3, 0xb3, 0xb0, 0xa5, 0xb5})
	types.RegisterSignature(types.KindWindowsEventLog, types.TypeNone, 0, []byte("ElfFile\x00"))
	types.RegisterSignature(types.KindWindowsEventViewer, types.TypeNone, 0, []byte{0x30, 0x00, 0x00, 0x00, 0x4c, 0x66, 0x4c, 0x65})
	types.RegisterSignature(types.KindWindowsHelp, types.TypeNone, 0, []byte("LN\x02\x00"))
	types.RegisterSignature(types.KindWindowsHibernationData, types.TypeNone, 0, []byte("hibr"))
	types.RegisterSignature(types.KindWindowsInternationalCodePage, types.TypeNone, 0, []byte{0xff, 0x46, 0x4f, 0x4e, 0x54})
	types.RegisterSignature(types.KindWindowsMemoryDump, types.TypeNone, 0, []byte("PAGEDU"))
	types.RegisterSignature(types.KindWindowsMinidump, types.TypeNone, 0, []byte("MDMP\x93\xa7"))
	types.RegisterSignature(types.KindWindowsPrecompiledHeader, types.TypeNone, 0, []byte("VCPCH0"))
	types.RegisterSignature(types.KindWindowsPrefetch, types.TypeNone, 0, []byte("MAM\x04"))
	types.RegisterSignature(types.KindWindowsPrefetch, types.TypeNone, 0, []byte{0x11, 0x00, 0x00, 0x00, 'S', 'C', 'C', 'A'})
	types.RegisterSignature(types.KindWindowsPrefetch, types.TypeNone, 4, []byte("SCCA"))
	types.RegisterSignature(types.KindWindowsProgramManagerGroup, types.TypeNone, 0, []byte("PMCC"))
	types.RegisterSignature(types.KindWindowsResource, types.TypeNone, 0, []byte{0x00, 0x00, 0x00, 0x00, 0x20, 0x00, 0x00, 0x00, 0xff, 0xff, 0x00, 0x00, 0xff, 0xff, 0x00, 0x00})
	types.RegisterSignature(types.KindWindowsShortcut, types.TypeNone, 0, []byte{0x4c, 0x00, 0x00, 0x00, 0x01, 0x14, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0xc0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x46})
	types.RegisterSignature(types.KindWindowsTypeLibrary, types.TypeNone, 0, []byte("MSFT\x02\x00\x01\x00"))
	types.RegisterSignature(types.KindWindowsUserStateMigration, types.TypeNone, 0, []byte("PMOCCMOC"))
	types.RegisterSignature(types.KindWinNTNetmonCapture, types.TypeNone, 0, []byte("RTSS"))
	types.RegisterSignature(types.KindWinNTRegistryUndo, types.TypeNone, 0, []byte("REGEDIT"))
	types.RegisterSignature(types.KindXboxISO, types.TypeNone, 0, []byte("XISO"))
	types.RegisterSignature(types.KindXCOFFExecutable, types.TypeNone, 0, []byte{0x01, 0xdf})
	types.RegisterSignature(types.KindXCOFFExecutable, types.TypeNone, 0, []byte{0x01, 0xf7})
	types.RegisterSignature(types.KindXFSFilesystem, types.TypeNone, 0, []byte("XFSB"))
	types.RegisterSignature(types.KindXPCOMLibraries, types.TypeNone, 0, []byte("XPCOM\nTy"))
	types.RegisterSignature(types.KindZXTape, types.TypeNone, 0, []byte("ZXTape!"))

	types.RegisterMaskedSignature(types.KindErlangBEAMBytecode, types.TypeNone, 0, []byte("FOR1\x00\x00\x00\x00BEAM"), []byte{0xff, 0xff, 0xff, 0xff, 0x00, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff})

	types.RegisterWeakSignature(types.KindMSDOSCOFFObject, types.TypeOBJ, 0, []byte{0x4c, 0x01})
}
