// Code generated by optimizer, DO NOT EDIT.
package types

var subtypeMap = map[KindID][]TypeID{
	KindAACAudio:              {TypeADTS},
	KindAcronisTrueImage:      {TypeB4, TypeCE},
	KindBerkeleyDatabase:      {TypeLittleEndian},
	KindBethesdaArchive:       {TypeBA2},
	KindBrotherEmbroidery:     {TypePEC, TypePES},
	KindCPIOArchive:           {TypeBinaryBigEndian, TypeBinaryLittleEndian, TypeNewASCII, TypeNewASCIIWithCRC, TypeOldASCII},
	KindCRXBrowserExtension:   {TypeVersion2, TypeVersion3},
	KindCanonRAWImage:         {TypeHE},
	KindDPXImage:              {TypeBigEndian, TypeLittleEndian},
	KindDalvikExecutable:      {TypeVersion035, TypeVersion036, TypeVersion037, TypeVersion038, TypeVersion039, TypeVersion040, TypeVersion041},
	KindEBMLContainer:         {TypeMatroskaVideo, TypeWebMVideo},
	KindFATFilesystem:         {TypeFAT12, TypeFAT16, TypeFAT32},
	KindGHCiInterface:         {Type32Bit, Type64Bit},
	KindGIFImage:              {TypeGIF87a, TypeGIF89a},
	KindGuitarProTablature:    {TypeVersion3, TypeVersion4, TypeVersion5},
	KindGzipData:              {TypeBGZF},
	KindHighEntropyData:       {TypeBinary, TypeEncrypted, TypeHighEntropy},
	KindICOCURImage:           {TypeWindowsCursor, TypeWindowsIcon},
	KindIFFContainer:          {TypeAIFCAudio, TypeAIFFAudio, TypeCAT, TypeILBMImage, TypeLIST, TypeWestwoodVQA},
	KindISOBaseMedia:          {Type3G2Video, Type3GPPVideo, TypeAVIFImage, TypeAVIFImageSequence, TypeBlackmagicRAWVideo, TypeCanonRAW3Image, TypeF4VVideo, TypeHEIFImage, TypeM4VVideo, TypeMP4Video, TypeMPEG4Audio, TypeMotionJPEG2000Video, TypeQuickTimeMovie},
	KindJPEG2000Image:         {TypeCodestream},
	KindJPEGXLImage:           {TypeCodestream, TypeContainer},
	KindJPEGXRImage:           {TypeBigEndian, TypeLittleEndian},
	KindKTXTextureImage:       {TypeVersion1, TypeVersion2},
	KindKeePassDatabase:       {TypeKDB, TypeKDBX},
	KindLLVMBitcode:           {TypeWrapper},
	KindLZ4Frame:              {TypeLZ4Legacy},
	KindMPEG2TransportStream:  {TypeM2TSBDAV},
	KindMPEGAudio:             {TypeMP3ID3Tagged, TypeMPEGLayer1, TypeMPEGLayer2, TypeMPEGLayer3},
	KindMPEGAudioFrame:        {TypeAC3, TypeEAC3},
	KindMPEGTransportStream:   {TypeNone},
	KindMPEGVideo:             {TypeMPEG12Video},
	KindMSDOSCOFFObject:       {TypeOBJ},
	KindMachOBinary:           {Type32BitBigEndian, Type32BitLittleEndian, Type64BitBigEndian, Type64BitLittleEndian},
	KindMachOUniversalBinary:  {Type64Bit},
	KindMetafileImage:         {TypeEnhancedMetafile, TypeWindowsMetafile},
	KindMusepackAudio:         {TypeVersion7, TypeVersion8},
	KindNetpbmImage:           {TypePAM, TypePBMASCII, TypePBMBinary, TypePGMASCII, TypePGMBinary, TypePPMASCII, TypePPMBinary},
	KindNintendo64ROM:         {TypeBigEndian, TypeByteSwapped, TypeLittleEndian},
	KindOLECompoundDocument:   {TypeMicrosoftExcelWorkbook, TypeMicrosoftInstaller, TypeMicrosoftInstallerPatch, TypeMicrosoftOutlookMessage, TypeMicrosoftPowerPointPresentation, TypeMicrosoftProjectDocument, TypeMicrosoftPublisherDocument, TypeMicrosoftVisioDrawing, TypeMicrosoftWordDocument},
	KindOggContainer:          {TypeFLACAudio, TypeOpusAudio, TypeSpeexAudio, TypeTheoraVideo, TypeVorbisAudio},
	KindPCAPCapture:           {TypeBigEndian, TypeLittleEndian, TypeNanosecondBigEndian, TypeNanosecondLittleEndian},
	KindPEMPrivateKey:         {TypeDSA, TypeEC, TypeRSA},
	KindPhotoshopDocument:     {TypePSB, TypePSD},
	KindPortableExecutable:    {TypeWindowsLE, TypeWindowsLX, TypeWindowsNE},
	KindQCOWDiskImage:         {TypeQCOW1, TypeQCOW2},
	KindRARArchive:            {TypeLegacy, TypeVersion5},
	KindRIFFContainer:         {TypeAVIVideo, TypeAfterEffectsProject, TypeCDAAudio, TypeCorelDRAWDocument, TypeCubaseProject, TypeDSIKModule, TypeDownloadableSounds, TypeHDPhoto, TypeMIDIAudio, TypeQCPAudio, TypeRF64Audio, TypeRIFFPalette, TypeSoundFont2, TypeWAVAudio, TypeWebPImage, TypeWindowsAnimatedCursor},
	KindRagePackageFormat:     {TypeRPF0, TypeRPF2, TypeRPF3, TypeRPF4, TypeRPF6, TypeRPF7},
	KindSQLite3WriteAheadLog:  {TypeBigEndian, TypeLittleEndian},
	KindSQLiteDatabase:        {TypeGeoPackage, TypeMBTiles},
	KindShockwaveFlash:        {TypeLZMACompressed, TypeUncompressed, TypeZlibCompressed},
	KindTARArchive:            {TypeArchLinuxPackage, TypeComicBook, TypeCondaPackage, TypeFlatpak, TypeNpmPackage, TypeOCIImageLayout, TypePythonSourceDistribution, TypeSlackwarePackage, TypeVagrantBox},
	KindTIFFImage:             {TypeAdobeDNG, TypeBigEndian, TypeBigTIFF, TypeLittleEndian, TypeNikonRAW, TypeOlympusRAW, TypePanasonicRAW, TypePentaxRAW, TypeSonyRAW, TypeSonyRAWSR2},
	KindVMwareDiskImage:       {TypeCOWD, TypeKDM, TypeVMDK, TypeVMDKDescription},
	KindVisualStudioSolution:  {TypeWorkspace},
	KindVulkanSPIRV:           {TypeBigEndian, TypeLittleEndian},
	KindWADArchive:            {TypeIWAD, TypePWAD},
	KindWebAssemblyModule:     {TypeASCII},
	KindWindowsThumbnailCache: {TypeIMMM},
	KindXMLDocument:           {TypeXSLTStylesheet},
	KindZIPArchive:            {Type3MFDocument, TypeAPPXPackage, TypeAndroidAppBundle, TypeAndroidArchive, TypeAndroidPackage, TypeAndroidPackageX, TypeAndroidSplitAPKSet, TypeAndroidSystemPackage, TypeBitwig, TypeCeltx, TypeComicBook, TypeEPUBDocument, TypeEmpty, TypeFabricMod, TypeFirefoxExtension, TypeForgeMod, TypeIOSApplicationArchive, TypeJavaArchive, TypeJavaEnterpriseArchive, TypeJavaWebArchive, TypeKMZArchive, TypeKerasModel, TypeKritaDocument, TypeLOVEGame, TypeMSIXPackage, TypeMicrosoftExcelAddIn, TypeMicrosoftExcelMacroEnabledTemplate, TypeMicrosoftExcelMacroEnabledWorkbook, TypeMicrosoftExcelTemplate, TypeMicrosoftExcelWorkbook, TypeMicrosoftPowerPointAddIn, TypeMicrosoftPowerPointMacroEnabledPresentation, TypeMicrosoftPowerPointMacroEnabledSlideshow, TypeMicrosoftPowerPointMacroEnabledTemplate, TypeMicrosoftPowerPointPresentation, TypeMicrosoftPowerPointSlideshow, TypeMicrosoftPowerPointTemplate, TypeMicrosoftWordDocument, TypeMicrosoftWordMacroEnabledDocument, TypeMicrosoftWordMacroEnabledTemplate, TypeMicrosoftWordTemplate, TypeMinecraftResourcePack, TypeNone, TypeNuGetPackage, TypeOpenDocumentChart, TypeOpenDocumentDatabase, TypeOpenDocumentFormula, TypeOpenDocumentGraphics, TypeOpenDocumentImage, TypeOpenDocumentPresentation, TypeOpenDocumentSpreadsheet, TypeOpenDocumentText, TypeOpenRasterImage, TypeOsuBeatmap, TypeOsuSkin, TypePSVita, TypeProcreate, TypePyTorchModel, TypePythonWheel, TypeStudioOne, TypeVisualStudioExtension, TypeXMLPaperSpecification},
	KindZstandardArchive:      {TypeSkinnableFrame},
}

type FormatInfo struct {
	Kind string
	Type string
}

func ListFormats() []FormatInfo {
	list := make([]FormatInfo, 0, 256)

	for i := range KindID(len(kindNames)) {
		name := kindNames[i]
		if name == "" || name == "Unknown" {
			continue
		}

		list = append(list, FormatInfo{Kind: name})

		if types, ok := subtypeMap[i]; ok {
			for _, t := range types {
				if tn := t.String(); tn != "" {
					list = append(list, FormatInfo{Kind: name, Type: tn})
				}
			}
		}
	}

	return list
}
