// Code generated by optimizer, DO NOT EDIT.
package types

var subtypeMap = map[KindID][]TypeID{
	KindAACAudio:              {TypeADTS},
	KindAcronisTrueImage:      {TypeB4, TypeCE},
	KindBerkeleyDB:            {TypeLittleEndian},
	KindBrotherEmbroidery:     {TypePEC, TypePES},
	KindCPIOArchive:           {TypeBinaryBigEndian, TypeBinaryLittleEndian, TypeNewASCII, TypeNewASCIIWithCRC, TypeOldASCII},
	KindCRXBrowserExtension:   {TypeCRXVersion2, TypeCRXVersion3},
	KindCanonRAWImage:         {TypeHE},
	KindComicBookArchive:      {TypeCBT, TypeCBZ},
	KindDPXImage:              {TypeBigEndian, TypeLittleEndian},
	KindDalvikExecutable:      {TypeDEX035, TypeDEX036, TypeDEX037, TypeDEX038, TypeDEX039, TypeDEX040, TypeDEX041},
	KindEBMLContainer:         {TypeMatroska, TypeWebM},
	KindFATFilesystem:         {TypeFAT12, TypeFAT16, TypeFAT32},
	KindGHCiInterface:         {Type32Bit, Type64Bit},
	KindGIFImage:              {TypeGIF87a, TypeGIF89a},
	KindGzipData:              {TypeBGZF},
	KindICOCURImage:           {TypeWindowsCursor, TypeWindowsIcon},
	KindIFFContainer:          {TypeAIFCAudio, TypeAIFFAudio, TypeCAT, TypeILBMImage, TypeLIST},
	KindISOBaseMedia:          {Type3G2Media, Type3GPPMedia, TypeAVIFImage, TypeAVIFImageSequence, TypeBlackmagicRAW, TypeCanonRAW3CR3, TypeF4VVideo, TypeHEIFImage, TypeM4VVideo, TypeMP4Video, TypeMPEG4AudioM4AFamily, TypeMotionJPEG2000, TypeQuickTimeMovie},
	KindJPEG2000Image:         {TypeCodestream},
	KindJPEGXLImage:           {TypeCodestream, TypeContainer},
	KindJPEGXRImage:           {TypeBigEndian, TypeLittleEndian},
	KindJavaModule:            {TypeJMOD},
	KindKTXTexture:            {TypeKTX, TypeKTX2},
	KindKeePassDatabase:       {TypeKDB, TypeKDBX},
	KindLLVMBitcode:           {TypeWrapper},
	KindLZ4Frame:              {TypeLZ4Legacy},
	KindMBOXEmailFolder:       {TypeReturnPath},
	KindMPEG2TransportStream:  {TypeM2TSBDAV},
	KindMPEGAudio:             {TypeMP3ID3Tagged, TypeMPEGLayer1, TypeMPEGLayer2, TypeMPEGLayer3},
	KindMPEGAudioFrame:        {TypeAC3, TypeEAC3},
	KindMPEGTransportStream:   {TypeTS},
	KindMPEGVideo:             {TypeMPEG12Video},
	KindMachOBinary:           {Type32BitBigEndian, Type32BitLittleEndian, Type64BitBigEndian, Type64BitLittleEndian},
	KindMachOUniversalBinary:  {Type64Bit},
	KindMetafileImage:         {TypeEnhancedMetafileEMF, TypeWindowsMetafileWMF},
	KindMicrosoftCompress:     {TypeSZ},
	KindMicrosoftJournal:      {TypeNB},
	KindMusepackAudio:         {TypeStreamVersion7, TypeStreamVersion8},
	KindNetpbmImage:           {TypePAM, TypePBMASCII, TypePBMBinary, TypePGMASCII, TypePGMBinary, TypePPMASCII, TypePPMBinary},
	KindNintendo64ROM:         {TypeBigEndian, TypeByteSwapped, TypeLittleEndian},
	KindOLECompoundDocument:   {TypeMicrosoftExcelWorkbookXLS, TypeMicrosoftInstallerMSI, TypeMicrosoftOutlookMessageMSG, TypeMicrosoftPowerPointPresentationPPT, TypeMicrosoftProjectDocumentMPP, TypeMicrosoftPublisherDocumentPUB, TypeMicrosoftVisioDrawingVSD, TypeMicrosoftWordDocumentDOC},
	KindOggContainer:          {TypeFLACAudio, TypeOpusAudio, TypeSpeexAudio, TypeTheoraVideo, TypeVorbisAudio},
	KindPCAPCapture:           {TypeBigEndian, TypeLittleEndian, TypeNanosecondBigEndian, TypeNanosecondLittleEndian},
	KindPEMPrivateKey:         {TypeDSAPrivateKey, TypeECPrivateKey, TypeRSAPrivateKey},
	KindPhotoshopDocument:     {TypePSB, TypePSD},
	KindPortableExecutable:    {TypeWindowsLE, TypeWindowsLX, TypeWindowsNE},
	KindQCOWDiskImage:         {TypeQCOW1, TypeQCOW2},
	KindRARArchive:            {TypeRAR4, TypeRAR5},
	KindRIFFContainer:         {TypeAVIVideo, TypeAfterEffectsProjectAEP, TypeCDAAudio, TypeCorelDRAWDocumentCDR, TypeCubaseProjectCPR, TypeDownloadableSounds, TypeQCPAudio, TypeRIFFMIDI, TypeRIFFPalette, TypeSoundFont2, TypeWAVAudio, TypeWebPImage, TypeWindowsAnimatedCursor},
	KindSQLite3WriteAheadLog:  {TypeBigEndian, TypeLittleEndian},
	KindShockwaveFlash:        {TypeLZMACompressed, TypeUncompressed, TypeZlibCompressed},
	KindSketchDocument:        {TypeSketchDocument},
	KindTARArchive:            {TypeArchLinuxPackage, TypeCwtfPackage, TypeNpmPackageTarball, TypeOCIImageLayoutTar, TypePythonSourceDistributionSDist, TypeSlackwarePackage, TypeVagrantBox},
	KindTIFFImage:             {TypeAdobeDNGDNG, TypeBigEndian, TypeBigTIFF, TypeLittleEndian, TypeNikonRAWNEF, TypePanasonicRAWRW2, TypePentaxRAWPEF, TypeSonyRAWARW, TypeSonyRAWSR2},
	KindTrueTypeFont:          {TypeTrue},
	KindVMwareDiskImage:       {TypeCOWD, TypeKDM, TypeVMDK, TypeVMDKDescription},
	KindVulkanSPIRV:           {TypeBigEndian, TypeLittleEndian},
	KindWADArchive:            {TypeIWAD, TypePWAD},
	KindWebAssemblyModule:     {TypeASCIIText},
	KindWindowsHelp:           {TypeLN},
	KindWindowsThumbnailCache: {TypeIMMM},
	KindXMLDocument:           {TypeXSLTStylesheet},
	KindZIPArchive:            {Type3MFDocument, TypeAPPXPackage, TypeAndroidAppBundleAAB, TypeAndroidArchiveAAR, TypeAndroidPackageAPK, TypeAndroidPackageXAPK, TypeAndroidSplitAPKS, TypeAndroidSystemPackageAPEX, TypeEPUBDocument, TypeEmpty, TypeFabricMod, TypeFirefoxExtensionXPI, TypeForgeMod, TypeIOSApplicationArchiveIPA, TypeJMOD, TypeJavaArchiveJAR, TypeJavaEnterpriseArchiveEAR, TypeJavaWebArchiveWAR, TypeKMZArchive, TypeKerasModel, TypeKritaDocumentKRA, TypeLOVEGame, TypeMSIXPackage, TypeMicrosoftExcelAddInXLAM, TypeMicrosoftExcelMacroEnabledTemplateXLTM, TypeMicrosoftExcelMacroEnabledWorkbookXLSM, TypeMicrosoftExcelSpreadsheetXLSX, TypeMicrosoftExcelTemplateXLTX, TypeMicrosoftPowerPointAddInPPAM, TypeMicrosoftPowerPointMacroEnabledPresentationPPTM, TypeMicrosoftPowerPointMacroEnabledSlideshowPPSM, TypeMicrosoftPowerPointMacroEnabledTemplatePOTM, TypeMicrosoftPowerPointPresentationPPTX, TypeMicrosoftPowerPointSlideshowPPSX, TypeMicrosoftPowerPointTemplatePOTX, TypeMicrosoftWordDocumentDOCX, TypeMicrosoftWordMacroEnabledDocumentDOCM, TypeMicrosoftWordMacroEnabledTemplateDOTM, TypeMicrosoftWordTemplateDOTX, TypeMinecraftResourcePack, TypeNuGetPackageNUPKG, TypeOpenDocumentChartODC, TypeOpenDocumentDatabaseODB, TypeOpenDocumentFormulaODF, TypeOpenDocumentGraphicsODG, TypeOpenDocumentImageODI, TypeOpenDocumentPresentationODP, TypeOpenDocumentSpreadsheetODS, TypeOpenDocumentTextODT, TypeOpenRasterImageORA, TypePyTorchModel, TypePythonWheelWHL, TypeSpanned, TypeVisualStudioExtensionVSIX, TypeXMLPaperSpecificationXPS},
	KindZstandardArchive:      {TypeZstandardSkinnableFrame},
}

type FormatInfo struct {
	Kind string
	Type string
}

func ListFormats() []FormatInfo {
	list := make([]FormatInfo, 0, 256)

	for i := KindID(0); i < KindID(len(kindNames)); i++ {
		name := kindNames[i]
		if name == "" || name == "Unknown" {
			continue
		}

		list = append(list, FormatInfo{Kind: name})

		if types, ok := subtypeMap[i]; ok {
			for _, t := range types {
				if tn := t.String(); tn != "" {
					list = append(list, FormatInfo{Kind: name, Type: tn})
				}
			}
		}
	}

	return list
}
