// Code generated by optimizer, DO NOT EDIT.
package types

import (
	"bytes"
	"encoding/binary"
	"slices"
	"unicode/utf8"
)

func DetectAC3(b Buffer) *Metadata {
	if b.Len() >= 6 && b[0] == 0x0b && b[1] == 0x77 {
		bsid := (b[5] >> 3) & 0x1f
		if bsid <= 10 {
			return &Metadata{Kind: KindMPEGAudioFrame, Type: TypeAC3}
		}

		return &Metadata{Kind: KindMPEGAudioFrame, Type: TypeEAC3}
	}

	return nil
}

func DetectAppleDiskImage(b Buffer) *Metadata {
	if b.Len() < 512 {
		return nil
	}

	if b.Has(b.Len()-512, []byte("koly")) {
		return &Metadata{
			Kind: KindAppleDiskImage,
		}
	}

	return nil
}

func DetectEBML(b Buffer) *Metadata {
	if !b.Has(0, []byte{0x1a, 0x45, 0xdf, 0xa3}) {
		return nil
	}

	limit := min(b.Len(), 256)
	data := b[:limit]

	if bytes.Contains(data, []byte("webm")) {
		return &Metadata{
			Kind: KindEBMLContainer,
			Type: TypeWebM,
		}
	}

	if bytes.Contains(data, []byte("matroska")) {
		return &Metadata{
			Kind: KindEBMLContainer,
			Type: TypeMatroska,
		}
	}

	return &Metadata{
		Kind: KindEBMLContainer,
	}
}

func DetectELF(b Buffer) *Metadata {
	if !b.Has(0, []byte{0x7f, 'E', 'L', 'F'}) {
		return nil
	}

	if b.Has(8, []byte{'A', 'I', 0x01}) || b.Has(8, []byte{'A', 'I', 0x02}) {
		return &Metadata{
			Kind: KindAppImage,
		}
	}

	class := byte(0)
	data := byte(0)

	if b.Len() > 4 {
		class = b[4]
	}

	if b.Len() > 5 {
		data = b[5]
	}

	typ := elfType(class, data)

	return &Metadata{
		Kind: KindExecutableAndLinkableFormat,
		Type: typ,
	}
}

func elfType(class byte, data byte) TypeID {
	switch class {
	case 1:
		switch data {
		case 1:
			return TypeELF32LittleEndian
		case 2:
			return TypeELF32BigEndian
		default:
			return TypeELF32
		}
	case 2:
		switch data {
		case 1:
			return TypeELF64LittleEndian
		case 2:
			return TypeELF64BigEndian
		default:
			return TypeELF64
		}
	default:
		return TypeELF
	}
}

const (
	superblockOffset = 1024
	magicOffset      = superblockOffset + 56
	compatOffset     = superblockOffset + 92
	incompatOffset   = superblockOffset + 96
	roCompatOffset   = superblockOffset + 100
)

func DetectExt(b Buffer) *Metadata {
	if b.Len() < superblockOffset+104 {
		return nil
	}

	magic, ok := b.U16LE(magicOffset)
	if !ok || magic != 0xef53 {
		return nil
	}

	compat, ok := b.U32LE(compatOffset)
	if !ok {
		return nil
	}

	incompat, ok := b.U32LE(incompatOffset)
	if !ok {
		return nil
	}

	roCompat, ok := b.U32LE(roCompatOffset)
	if !ok {
		return nil
	}

	typ := TypeExt2

	if incompat&0x40 != 0 {
		typ = TypeExt4
	} else if compat&0x4 != 0 || roCompat&0x4 != 0 {
		typ = TypeExt3
	}

	return &Metadata{
		Kind: KindExtFilesystem,
		Type: typ,
	}
}

func DetectFAT(b Buffer) *Metadata {
	if b.Len() < 90 {
		return nil
	}

	if !((b[0] == 0xeb && b[2] == 0x90) || b[0] == 0xe9) {
		return nil
	}

	bps, ok := b.U16LE(11)
	if !ok || (bps != 512 && bps != 1024 && bps != 2048 && bps != 4096) {
		return nil
	}

	spc := b[13]
	if spc == 0 || (spc&(spc-1)) != 0 {
		return nil
	}

	fats := b[16]
	if fats == 0 || fats > 4 {
		return nil
	}

	if b.Has(82, []byte("FAT32   ")) {
		return &Metadata{Kind: KindFATFilesystem, Type: TypeFAT32}
	}

	if b.Has(54, []byte("FAT12   ")) {
		return &Metadata{Kind: KindFATFilesystem, Type: TypeFAT12}
	}

	if b.Has(54, []byte("FAT16   ")) {
		return &Metadata{Kind: KindFATFilesystem, Type: TypeFAT16}
	}

	return nil
}

func DetectISOBaseMedia(b Buffer) *Metadata {
	if b.Len() < 12 {
		return nil
	}

	boxSize32, ok := b.U32BE(0)
	if !ok || !b.Has(4, []byte("ftyp")) {
		return nil
	}

	brandOffset := 8
	compatibleOffset := 16
	boxEnd := int(boxSize32)

	if boxSize32 == 1 {
		high, ok := b.U32BE(8)
		if !ok || high != 0 {
			return nil
		}

		low, ok := b.U32BE(12)
		if !ok {
			return nil
		}

		boxEnd = int(low)
		brandOffset = 16
		compatibleOffset = 24
	}

	if boxEnd <= compatibleOffset {
		return nil
	}

	if boxEnd > b.Len() {
		boxEnd = b.Len()
	}

	if !hasISOBrand(b, brandOffset, compatibleOffset, boxEnd, "isom", "iso2", "iso3", "iso4", "iso5", "iso6", "mp41", "mp42", "dash", "avif", "avis", "heic", "heix", "hevc", "hevx", "mif1", "msf1", "mjp2", "M4A ", "M4B ", "M4P ", "M4V ", "f4v ", "qt  ", "3gp4", "3gp5", "3gp6", "3gs7", "3ge6", "3gg6", "3gp1", "3gp2", "3g2a", "3g2b", "crx ", "braw", "MSNV") {
		return nil
	}

	var majorBrand string

	if brandOffset+4 <= b.Len() {
		majorBrand = string(b[brandOffset : brandOffset+4])
	}

	switch majorBrand {
	case "qt  ":
		return &Metadata{Kind: KindISOBaseMedia, Type: TypeQuickTimeMovie}
	case "M4V ":
		return &Metadata{Kind: KindISOBaseMedia, Type: TypeM4VVideo}
	case "f4v ":
		return &Metadata{Kind: KindISOBaseMedia, Type: TypeF4VVideo}
	case "M4A ", "M4B ", "M4P ":
		return &Metadata{Kind: KindISOBaseMedia, Type: TypeMPEG4AudioM4AFamily}
	case "avif":
		return &Metadata{Kind: KindISOBaseMedia, Type: TypeAVIFImage}
	case "avis":
		return &Metadata{Kind: KindISOBaseMedia, Type: TypeAVIFImageSequence}
	case "heic", "heix", "hevc", "hevx", "mif1", "msf1":
		return &Metadata{Kind: KindISOBaseMedia, Type: TypeHEIFImage}
	case "mjp2":
		return &Metadata{Kind: KindISOBaseMedia, Type: TypeMotionJPEG2000}
	case "crx ":
		return &Metadata{Kind: KindISOBaseMedia, Type: TypeCanonRAW3}
	case "braw":
		return &Metadata{Kind: KindISOBaseMedia, Type: TypeBlackmagicRAW}
	case "3g2a", "3g2b":
		return &Metadata{Kind: KindISOBaseMedia, Type: Type3G2Media}
	}

	if len(majorBrand) == 4 && (majorBrand[:3] == "3gp" || majorBrand[:3] == "3g2") {
		if majorBrand[3] >= '1' && majorBrand[3] <= '9' {
			return &Metadata{Kind: KindISOBaseMedia, Type: Type3GPPMedia}
		}
	}

	if hasISOBrand(b, brandOffset, compatibleOffset, boxEnd, "avif") {
		return &Metadata{Kind: KindISOBaseMedia, Type: TypeAVIFImage}
	}

	if hasISOBrand(b, brandOffset, compatibleOffset, boxEnd, "avis") {
		return &Metadata{Kind: KindISOBaseMedia, Type: TypeAVIFImageSequence}
	}

	if hasISOBrand(b, brandOffset, compatibleOffset, boxEnd, "heic", "heix", "hevc", "hevx", "mif1", "msf1") {
		return &Metadata{Kind: KindISOBaseMedia, Type: TypeHEIFImage}
	}

	if hasISOBrand(b, brandOffset, compatibleOffset, boxEnd, "M4V ") {
		return &Metadata{Kind: KindISOBaseMedia, Type: TypeM4VVideo}
	}

	if hasISOBrand(b, brandOffset, compatibleOffset, boxEnd, "f4v ") {
		return &Metadata{Kind: KindISOBaseMedia, Type: TypeF4VVideo}
	}

	if hasISOBrand(b, brandOffset, compatibleOffset, boxEnd, "3g2a", "3g2b") {
		return &Metadata{Kind: KindISOBaseMedia, Type: Type3G2Media}
	}

	if hasISOBrandPrefix(b, brandOffset, compatibleOffset, boxEnd, "3gp", "3g2") {
		return &Metadata{Kind: KindISOBaseMedia, Type: Type3GPPMedia}
	}

	if hasISOBrand(b, brandOffset, compatibleOffset, boxEnd, "M4A ", "M4B ", "M4P ") {
		return &Metadata{Kind: KindISOBaseMedia, Type: TypeMPEG4AudioM4AFamily}
	}

	if hasISOBrand(b, brandOffset, compatibleOffset, boxEnd, "qt  ") {
		return &Metadata{Kind: KindISOBaseMedia, Type: TypeQuickTimeMovie}
	}

	if hasISOBrand(b, brandOffset, compatibleOffset, boxEnd, "mjp2") {
		return &Metadata{Kind: KindISOBaseMedia, Type: TypeMotionJPEG2000}
	}

	if hasISOBrand(b, brandOffset, compatibleOffset, boxEnd, "crx ") {
		return &Metadata{Kind: KindISOBaseMedia, Type: TypeCanonRAW3}
	}

	if hasISOBrand(b, brandOffset, compatibleOffset, boxEnd, "braw") {
		return &Metadata{Kind: KindISOBaseMedia, Type: TypeBlackmagicRAW}
	}

	if hasISOBrand(b, brandOffset, compatibleOffset, boxEnd, "isom", "iso2", "iso3", "iso4", "iso5", "iso6", "mp41", "mp42", "dash") {
		return &Metadata{Kind: KindISOBaseMedia, Type: TypeMP4Video}
	}

	return &Metadata{
		Kind: KindISOBaseMedia,
	}
}

func hasISOBrand(b Buffer, majorOffset int, compatOffset int, boxEnd int, brands ...string) bool {
	if majorOffset+4 <= b.Len() {
		if slices.Contains(brands, string(b[majorOffset:majorOffset+4])) {
			return true
		}
	}

	for off := compatOffset; off+4 <= boxEnd && off+4 <= b.Len(); off += 4 {
		if slices.Contains(brands, string(b[off:off+4])) {
			return true
		}
	}

	return false
}

func hasISOBrandPrefix(b Buffer, majorOffset int, compatOffset int, boxEnd int, prefixes ...string) bool {
	if majorOffset+3 <= b.Len() {
		if slices.Contains(prefixes, string(b[majorOffset:majorOffset+3])) {
			return true
		}
	}

	for off := compatOffset; off+4 <= boxEnd && off+4 <= b.Len(); off += 4 {
		if slices.Contains(prefixes, string(b[off:off+3])) {
			return true
		}
	}

	return false
}

func DetectJSON(b Buffer) *Metadata {
	limit := min(b.Len(), 4096)
	data := b[:limit]

	trimmed := bytes.TrimSpace(data)
	if len(trimmed) < 2 {
		return nil
	}

	if trimmed[0] == '{' || trimmed[0] == '[' {
		if bytes.Contains(trimmed, []byte(`":`)) || bytes.Contains(trimmed, []byte(`": `)) {
			return &Metadata{Kind: KindJSONDocument, Confidence: ConfidenceMedium}
		}
	}

	return nil
}

func DetectLZMA(b Buffer) *Metadata {
	if b.Len() < 13 {
		return nil
	}

	props := b[0]
	if props > 224 {
		return nil
	}

	dictSize, ok := b.U32LE(1)
	if !ok {
		return nil
	}

	if dictSize == 0 {
		return nil
	}

	if dictSize > (1 << 30) {
		return nil
	}

	if b.Len() > 13 && b[13] != 0x00 {
		return nil
	}

	uncompressedSize := binary.LittleEndian.Uint64(b[5:13])

	if uncompressedSize != ^uint64(0) && uncompressedSize > (1<<40) {
		return nil
	}

	return &Metadata{
		Kind:       KindLZMAData,
		Confidence: ConfidenceMedium,
	}
}

func DetectMachO(b Buffer) *Metadata {
	if b.Has(0, []byte{0xfe, 0xed, 0xfa, 0xce}) {
		if !isValidMachOHeaderBE(b, 4) {
			return nil
		}

		return &Metadata{
			Kind: KindMachOBinary,
			Type: Type32BitBigEndian,
		}
	}

	if b.Has(0, []byte{0xce, 0xfa, 0xed, 0xfe}) {
		if !isValidMachOHeaderLE(b, 4) {
			return nil
		}

		return &Metadata{
			Kind: KindMachOBinary,
			Type: Type32BitLittleEndian,
		}
	}

	if b.Has(0, []byte{0xfe, 0xed, 0xfa, 0xcf}) {
		if !isValidMachOHeaderBE(b, 4) {
			return nil
		}

		return &Metadata{
			Kind: KindMachOBinary,
			Type: Type64BitBigEndian,
		}
	}

	if b.Has(0, []byte{0xcf, 0xfa, 0xed, 0xfe}) {
		if !isValidMachOHeaderLE(b, 4) {
			return nil
		}

		return &Metadata{
			Kind: KindMachOBinary,
			Type: Type64BitLittleEndian,
		}
	}

	if b.Has(0, []byte{0xca, 0xfe, 0xba, 0xbe}) {

		if b.Len() >= 8 {
			majorVersion, ok := b.U16BE(6)
			if ok && majorVersion >= 45 && majorVersion <= 75 {
				return &Metadata{Kind: KindJavaClass}
			}
		}

		if !isValidFatArchCPUType(b, 8) {
			return nil
		}

		return &Metadata{
			Kind: KindMachOUniversalBinary,
		}
	}

	if b.Has(0, []byte{0xca, 0xfe, 0xba, 0xbf}) {
		nfatArch, ok := b.U32BE(4)
		if !ok {
			return nil
		}

		if nfatArch == 0 || nfatArch > 32 {
			return nil
		}

		if !isValidFatArchCPUType(b, 8) {
			return nil
		}

		return &Metadata{
			Kind: KindMachOUniversalBinary,
			Type: Type64Bit,
		}
	}

	return nil
}

func isValidMachOHeaderBE(b Buffer, cpuOffset int) bool {
	cpuType, ok := b.U32BE(cpuOffset)
	if !ok {
		return false
	}

	return isKnownMachOCPUType(cpuType)
}

func isValidMachOHeaderLE(b Buffer, cpuOffset int) bool {
	cpuType, ok := b.U32LE(cpuOffset)
	if !ok {
		return false
	}

	return isKnownMachOCPUType(cpuType)
}

func isValidFatArchCPUType(b Buffer, cpuOffset int) bool {
	cpuType, ok := b.U32BE(cpuOffset)
	if !ok {
		return false
	}

	return isKnownMachOCPUType(cpuType)
}

func isKnownMachOCPUType(cpuType uint32) bool {
	masked := cpuType & 0x00ffffff

	switch masked {
	case 6, 7, 12, 14, 18:
		return true
	default:
		return false
	}
}

func DetectMP3(b Buffer) *Metadata {
	if b.Len() < 4 {
		return nil
	}

	if b[0] != 0xff || (b[1]&0xe0) != 0xe0 {
		return nil
	}

	version := (b[1] >> 3) & 0x03
	layer := (b[1] >> 1) & 0x03
	bitrate := (b[2] >> 4) & 0x0f
	sampleRate := (b[2] >> 2) & 0x03

	if version == 1 || layer == 0 || bitrate == 0 || bitrate == 0x0f || sampleRate == 0x03 {
		return nil
	}

	if layer == 1 {
		return &Metadata{Kind: KindMPEGAudio, Type: TypeMPEGLayer3, Confidence: ConfidenceMedium}
	}

	if layer == 2 {
		return &Metadata{Kind: KindMPEGAudio, Type: TypeMPEGLayer2, Confidence: ConfidenceMedium}
	}

	if layer == 3 {
		return &Metadata{Kind: KindMPEGAudio, Type: TypeMPEGLayer1, Confidence: ConfidenceMedium}
	}

	return nil
}

func DetectMPEGTransport(b Buffer) *Metadata {
	if b.Len() >= 3*188 && b[0] == 0x47 && b[188] == 0x47 && b[376] == 0x47 {
		return &Metadata{Kind: KindMPEGTransportStream, Type: TypeNone, Confidence: ConfidenceMedium}
	}

	if b.Len() >= 4+3*192 && b[4] == 0x47 && b[196] == 0x47 && b[388] == 0x47 {
		return &Metadata{Kind: KindMPEG2TransportStream, Type: TypeM2TSBDAV, Confidence: ConfidenceMedium}
	}

	return nil
}

func DetectNetpbm(b Buffer) *Metadata {
	if b.Len() < 3 {
		return nil
	}

	if b[0] != 'P' {
		return nil
	}

	if !isNetpbmDelimiter(b[2]) {
		return nil
	}

	switch b[1] {
	case '1':
		return &Metadata{
			Kind: KindNetpbmImage,
			Type: TypePBMASCII,
		}
	case '2':
		return &Metadata{
			Kind: KindNetpbmImage,
			Type: TypePGMASCII,
		}
	case '3':
		return &Metadata{
			Kind: KindNetpbmImage,
			Type: TypePPMASCII,
		}
	case '4':
		return &Metadata{
			Kind: KindNetpbmImage,
			Type: TypePBMBinary,
		}
	case '5':
		return &Metadata{
			Kind: KindNetpbmImage,
			Type: TypePGMBinary,
		}
	case '6':
		return &Metadata{
			Kind: KindNetpbmImage,
			Type: TypePPMBinary,
		}
	case '7':
		return &Metadata{
			Kind: KindNetpbmImage,
			Type: TypePAM,
		}
	default:
		return nil
	}
}

func isNetpbmDelimiter(c byte) bool {
	switch c {
	case ' ', '\t', '\r', '\n', '\f':
		return true
	default:
		return false
	}
}

func DetectOgg(b Buffer) *Metadata {
	if !b.Has(0, []byte("OggS")) {
		return nil
	}

	limit := min(b.Len(), 4096)
	data := b[:limit]

	switch {
	case bytes.Contains(data, []byte("OpusHead")):
		return &Metadata{Kind: KindOggContainer, Type: TypeOpusAudio}
	case bytes.Contains(data, []byte{0x01, 'v', 'o', 'r', 'b', 'i', 's'}):
		return &Metadata{Kind: KindOggContainer, Type: TypeVorbisAudio}
	case bytes.Contains(data, []byte("Speex   ")):
		return &Metadata{Kind: KindOggContainer, Type: TypeSpeexAudio}
	case bytes.Contains(data, []byte{0x80, 't', 'h', 'e', 'o', 'r', 'a'}):
		return &Metadata{Kind: KindOggContainer, Type: TypeTheoraVideo}
	case bytes.Contains(data, []byte{0x7f, 'F', 'L', 'A', 'C'}):
		return &Metadata{Kind: KindOggContainer, Type: TypeFLACAudio}
	default:
		return &Metadata{Kind: KindOggContainer}
	}
}

var (
	oleWordDocument       = []byte{'W', 0, 'o', 0, 'r', 0, 'd', 0, 'D', 0, 'o', 0, 'c', 0, 'u', 0, 'm', 0, 'e', 0, 'n', 0, 't', 0, 0, 0}
	oleWorkbook           = []byte{'W', 0, 'o', 0, 'r', 0, 'k', 0, 'b', 0, 'o', 0, 'o', 0, 'k', 0, 0, 0}
	oleBook               = []byte{'B', 0, 'o', 0, 'o', 0, 'k', 0, 0, 0}
	olePowerPointDocument = []byte{'P', 0, 'o', 0, 'w', 0, 'e', 0, 'r', 0, 'P', 0, 'o', 0, 'i', 0, 'n', 0, 't', 0, ' ', 0, 'D', 0, 'o', 0, 'c', 0, 'u', 0, 'm', 0, 'e', 0, 'n', 0, 't', 0, 0, 0}
	oleMSI                = []byte{0x84, 0x10, 0x0c, 0x00, 0x00, 0x00, 0x00, 0x00, 0xc0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x46}
	oleMSP                = []byte{'M', 0, 'S', 0, 'P', 0}
	oleOutlookMessage     = []byte{'_', 0, '_', 0, 's', 0, 'u', 0, 'b', 0, 's', 0, 't', 0, 'g', 0, '1', 0, '.', 0, '0', 0, '_', 0}
	oleVisioDocument      = []byte{'V', 0, 'i', 0, 's', 0, 'i', 0, 'o', 0, 'D', 0, 'o', 0, 'c', 0, 'u', 0, 'm', 0, 'e', 0, 'n', 0, 't', 0}
	oleProject            = []byte{'M', 0, 'S', 0, 'P', 0, 'r', 0, 'o', 0, 'j', 0, 'e', 0, 'c', 0, 't', 0, '.', 0, 'P', 0, 'r', 0, 'o', 0, 'j', 0, 'e', 0, 'c', 0, 't', 0}
	olePublisher          = []byte{'P', 0, 'u', 0, 'b', 0, 'l', 0, 'i', 0, 's', 0, 'h', 0, 'e', 0, 'r', 0, 'D', 0, 'o', 0, 'c', 0, 'u', 0, 'm', 0, 'e', 0, 'n', 0, 't', 0}
)

func DetectOLE(b Buffer) *Metadata {
	if !b.Has(0, []byte{0xd0, 0xcf, 0x11, 0xe0, 0xa1, 0xb1, 0x1a, 0xe1}) {
		return nil
	}

	if bytes.Contains(b, oleWordDocument) || bytes.Contains(b, []byte("MSWordDoc")) || bytes.Contains(b, []byte("Word.Document.")) {
		return &Metadata{Kind: KindOLECompoundDocument, Type: TypeMicrosoftWordDocument}
	}

	if bytes.Contains(b, oleWorkbook) || bytes.Contains(b, oleBook) || bytes.Contains(b, []byte("Excel.Sheet.")) {
		return &Metadata{Kind: KindOLECompoundDocument, Type: TypeMicrosoftExcelWorkbook}
	}

	if bytes.Contains(b, olePowerPointDocument) || bytes.Contains(b, []byte("PowerPoint.Show.")) {
		return &Metadata{Kind: KindOLECompoundDocument, Type: TypeMicrosoftPowerPointPresentation}
	}

	if bytes.Contains(b, oleMSI) {
		return &Metadata{Kind: KindOLECompoundDocument, Type: TypeMicrosoftInstaller}
	}

	if bytes.Contains(b, oleMSP) {
		return &Metadata{Kind: KindOLECompoundDocument, Type: TypeMicrosoftInstallerPatch}
	}

	if bytes.Contains(b, oleOutlookMessage) {
		return &Metadata{Kind: KindOLECompoundDocument, Type: TypeMicrosoftOutlookMessage}
	}

	if bytes.Contains(b, oleVisioDocument) {
		return &Metadata{Kind: KindOLECompoundDocument, Type: TypeMicrosoftVisioDrawing}
	}

	if bytes.Contains(b, oleProject) {
		return &Metadata{Kind: KindOLECompoundDocument, Type: TypeMicrosoftProjectDocument}
	}

	if bytes.Contains(b, olePublisher) {
		return &Metadata{Kind: KindOLECompoundDocument, Type: TypeMicrosoftPublisherDocument}
	}

	return &Metadata{
		Kind: KindOLECompoundDocument,
	}
}

func DetectPCX(b Buffer) *Metadata {
	if b.Len() < 128 || b[0] != 0x0a {
		return nil
	}

	if !isPCXVersion(b[1]) {
		return nil
	}

	if b[2] != 1 {
		return nil
	}

	if !isPCXBitsPerPixel(b[3]) {
		return nil
	}

	xMin, ok := b.U16LE(4)
	if !ok {
		return nil
	}

	yMin, ok := b.U16LE(6)
	if !ok {
		return nil
	}

	xMax, ok := b.U16LE(8)
	if !ok {
		return nil
	}

	yMax, ok := b.U16LE(10)
	if !ok {
		return nil
	}

	if xMax < xMin || yMax < yMin {
		return nil
	}

	if b[64] != 0 {
		return nil
	}

	if !isPCXColorPlanes(b[65]) {
		return nil
	}

	bytesPerLine, ok := b.U16LE(66)
	if !ok || bytesPerLine == 0 {
		return nil
	}

	return &Metadata{
		Kind:       KindPCXImage,
		Confidence: ConfidenceMedium,
	}
}

func isPCXVersion(v byte) bool {
	switch v {
	case 0, 2, 3, 4, 5:
		return true
	default:
		return false
	}
}

func isPCXBitsPerPixel(v byte) bool {
	switch v {
	case 1, 2, 4, 8:
		return true
	default:
		return false
	}
}

func isPCXColorPlanes(v byte) bool {
	switch v {
	case 1, 3, 4:
		return true
	default:
		return false
	}
}

func DetectPE(b Buffer) *Metadata {
	if !b.Has(0, []byte{'M', 'Z'}) {
		return nil
	}

	peOff, ok := b.U32LE(0x3c)
	if !ok {
		return &Metadata{Kind: KindDOSExecutable}
	}

	off := int(peOff)

	if b.Has(off, []byte{'P', 'E', 0, 0}) {
		machine, ok := b.U16LE(off + 4)
		if !ok {
			return &Metadata{Kind: KindPortableExecutable}
		}

		magic, ok := b.U16LE(off + 24)
		if !ok {
			return &Metadata{Kind: KindPortableExecutable}
		}

		var typ TypeID

		switch magic {
		case 0x10b:
			typ = pe32MachineType(machine)
		case 0x20b:
			typ = pe32PlusMachineType(machine)
		default:
			return &Metadata{Kind: KindPortableExecutable}
		}

		return &Metadata{
			Kind: KindPortableExecutable,
			Type: typ,
		}
	}

	if b.Has(off, []byte{'N', 'E'}) {
		return &Metadata{Kind: KindPortableExecutable, Type: TypeWindowsNE}
	}

	if b.Has(off, []byte{'L', 'E'}) {
		return &Metadata{Kind: KindPortableExecutable, Type: TypeWindowsLE}
	}

	if b.Has(off, []byte{'L', 'X'}) {
		return &Metadata{Kind: KindPortableExecutable, Type: TypeWindowsLX}
	}

	return &Metadata{Kind: KindDOSExecutable}
}

func pe32MachineType(machine uint16) TypeID {
	switch machine {
	case 0x014c:
		return TypePE32X86
	case 0x8664:
		return TypePE32X8664
	case 0x01c0:
		return TypePE32ARM
	case 0x01c4:
		return TypePE32ARMv7
	case 0xaa64:
		return TypePE32ARM64
	case 0x0200:
		return TypePE32Itanium
	default:
		return TypePE32Unknown
	}
}

func pe32PlusMachineType(machine uint16) TypeID {
	switch machine {
	case 0x8664:
		return TypePE32PlusX8664
	case 0xaa64:
		return TypePE32PlusARM64
	default:
		return TypePE32PlusUnknown
	}
}

func DetectPKCS12(b Buffer) *Metadata {
	if b.Len() < 32 || b[0] != 0x30 {
		return nil
	}

	limit := min(b.Len(), 4096)
	if !bytes.Contains(b[:limit], []byte{0x06, 0x09, 0x2a, 0x86, 0x48, 0x86, 0xf7, 0x0d, 0x01, 0x07, 0x01}) {
		return nil
	}

	return &Metadata{Kind: KindPKCS12}
}

var pycMagic = map[uint16]struct{}{
	20121: {}, 50428: {}, 50823: {}, 60202: {}, 60717: {}, 62011: {},
	62021: {}, 62041: {}, 62051: {}, 62061: {}, 62071: {}, 62081: {},
	62091: {}, 62092: {}, 62101: {}, 62111: {}, 62121: {}, 62131: {},
	62151: {}, 62161: {}, 62171: {}, 62181: {}, 62191: {}, 62201: {},
	62211: {}, 3000: {}, 3010: {}, 3020: {}, 3030: {}, 3040: {},
	3050: {}, 3060: {}, 3061: {}, 3071: {}, 3081: {}, 3091: {},
	3101: {}, 3103: {}, 3111: {}, 3131: {}, 3141: {}, 3151: {},
	3160: {}, 3170: {}, 3180: {}, 3190: {}, 3200: {}, 3210: {},
	3220: {}, 3230: {}, 3250: {}, 3260: {}, 3270: {}, 3280: {},
	3290: {}, 3300: {}, 3310: {}, 3320: {}, 3330: {}, 3340: {},
	3350: {}, 3360: {}, 3370: {}, 3390: {}, 3400: {}, 3410: {},
	3420: {}, 3430: {}, 3450: {}, 3460: {}, 3470: {}, 3490: {},
	3500: {}, 3510: {}, 3520: {}, 3530: {},
}

func DetectPYC(b Buffer) *Metadata {
	if b.Len() < 4 {
		return nil
	}

	if b[2] != 0x0d || b[3] != 0x0a {
		return nil
	}

	magic, ok := b.U16LE(0)
	if !ok {
		return nil
	}

	if _, found := pycMagic[magic]; !found {
		return nil
	}

	return &Metadata{
		Kind: KindPythonBytecode,
	}
}

func DetectSQLiteSHM(b Buffer) *Metadata {
	if b.Len() < 96 {
		return nil
	}

	if !bytes.Equal(b[:48], b[48:96]) {
		return nil
	}

	var typ TypeID

	if b[0] == 0x18 {
		typ = TypeLittleEndian
	} else if b[3] == 0x18 {
		typ = TypeBigEndian
	} else {
		return nil
	}

	return &Metadata{
		Kind: KindSQLite3SharedMemory,
		Type: typ,
	}
}

func DetectTar(b Buffer) *Metadata {
	var isTar bool

	for offset := 0; offset+512 <= b.Len(); offset += 512 {
		if b.Len() >= offset+262 && string(b[offset+257:offset+262]) == "ustar" {
			isTar = true

			nameEnd := bytes.IndexByte(b[offset:offset+100], 0)
			if nameEnd == -1 {
				nameEnd = 100
			}

			if nameEnd > 0 {
				switch string(b[offset : offset+nameEnd]) {
				case "package/package.json", "package.json":
					return &Metadata{Kind: KindTARArchive, Type: TypeNpmPackageTarball}
				case "oci-layout", "index.json", "manifest.json":
					return &Metadata{Kind: KindTARArchive, Type: TypeOCIImageLayoutTar}
				case "PKG-INFO", "setup.py", "pyproject.toml":
					return &Metadata{Kind: KindTARArchive, Type: TypePythonSourceDistribution}
				case "info/index.json":
					return &Metadata{Kind: KindTARArchive, Type: TypeCondaPackage}
				case ".PKGINFO":
					return &Metadata{Kind: KindTARArchive, Type: TypeArchLinuxPackage}
				case "Vagrantfile":
					return &Metadata{Kind: KindTARArchive, Type: TypeVagrantBox}
				case "install/doinst.sh":
					return &Metadata{Kind: KindTARArchive, Type: TypeSlackwarePackage}
				case "ComicInfo.xml", "comicinfo.xml":
					return &Metadata{Kind: KindComicBookArchive, Type: TypeCBT}
				}
			}
		}
	}

	if isTar {
		return &Metadata{Kind: KindTARArchive}
	}

	return nil
}

func DetectText(b Buffer) *Metadata {
	if b.Len() == 0 {
		return nil
	}

	if !passesTextLengthGate(b) {
		return nil
	}

	var (
		isASCII  bool
		isUTF8   bool
		textData []byte
	)

	if b.Has(0, []byte{0xef, 0xbb, 0xbf}) {
		textData = b[3:]

		isUTF8 = isLikelyTextUTF8(textData)
	} else {
		textData = b

		isASCII = isLikelyASCIIText(textData)
		if !isASCII {
			isUTF8 = isLikelyTextUTF8(textData)
		}
	}

	if !isASCII && !isUTF8 {
		return nil
	}

	limit := min(len(textData), 4096)
	subtype := detectTextSubtype(textData[:limit])

	if subtype != TypeNone {
		return &Metadata{
			Kind:       KindTextFile,
			Type:       subtype,
			Confidence: ConfidenceMedium,
		}
	}

	fallbackType := TypeUTF8Text
	if isASCII {
		fallbackType = TypeASCIIText
	}

	return &Metadata{
		Kind:       KindTextFile,
		Type:       fallbackType,
		Confidence: ConfidenceLow,
	}
}

func detectTextSubtype(data []byte) TypeID {
	trimmed := bytes.TrimSpace(data)
	if len(trimmed) == 0 {
		return TypeNone
	}

	if bytes.HasPrefix(data, []byte("#!")) {
		lineEnd := bytes.IndexByte(data, '\n')
		if lineEnd == -1 {
			lineEnd = len(data)
		}

		shebang := data[:lineEnd]

		if bytes.Contains(shebang, []byte("bash")) || bytes.Contains(shebang, []byte("sh")) {
			return TypeBashScript
		}

		if bytes.Contains(shebang, []byte("python")) {
			return TypePython
		}

		if bytes.Contains(shebang, []byte("node")) {
			return TypeJavaScript
		}

		if bytes.Contains(shebang, []byte("perl")) {
			return TypePerl
		}

		if bytes.Contains(shebang, []byte("ruby")) {
			return TypeRuby
		}

		if bytes.Contains(shebang, []byte("php")) {
			return TypePHP
		}

		if bytes.Contains(shebang, []byte("lua")) {
			return TypeLua
		}

		if bytes.Contains(shebang, []byte("Rscript")) {
			return TypeR
		}
	}

	if bytes.HasPrefix(trimmed, []byte("<?php")) {
		return TypePHP
	}

	if bytes.HasPrefix(trimmed, []byte("FROM ")) || bytes.HasPrefix(trimmed, []byte("# syntax=")) {
		return TypeDocker
	}

	if bytes.HasPrefix(trimmed, []byte("# ")) || bytes.HasPrefix(trimmed, []byte("## ")) {
		return TypeMarkdown
	}

	if bytes.HasPrefix(trimmed, []byte("---\n")) || bytes.HasPrefix(trimmed, []byte("---\r\n")) {
		if bytes.Contains(trimmed, []byte("title:")) || bytes.Contains(trimmed, []byte("layout:")) {
			return TypeMarkdown
		}

		return TypeYAML
	}

	if bytes.HasPrefix(trimmed, []byte("CREATE TABLE")) || bytes.HasPrefix(trimmed, []byte("SELECT ")) || bytes.HasPrefix(trimmed, []byte("INSERT INTO")) || bytes.HasPrefix(trimmed, []byte("-- SQL")) {
		return TypeSQL
	}

	if bytes.HasPrefix(trimmed, []byte("@echo off")) || bytes.HasPrefix(trimmed, []byte("@ECHO OFF")) || bytes.HasPrefix(trimmed, []byte("REM ")) || bytes.HasPrefix(trimmed, []byte("rem ")) {
		return TypeBatch
	}

	if bytes.HasPrefix(trimmed, []byte("cmake_minimum_required")) || bytes.HasPrefix(trimmed, []byte("project(")) {
		return TypeCMake
	}

	if bytes.HasPrefix(trimmed, []byte("body {")) || bytes.HasPrefix(trimmed, []byte("@import url(")) || bytes.HasPrefix(trimmed, []byte("@media ")) || bytes.HasPrefix(trimmed, []byte(":root {")) {
		return TypeCSS
	}

	if bytes.HasPrefix(trimmed, []byte("resource \"")) || bytes.HasPrefix(trimmed, []byte("variable \"")) || bytes.HasPrefix(trimmed, []byte("provider \"")) || bytes.HasPrefix(trimmed, []byte("terraform {")) {
		return TypeTerraform
	}

	if bytes.HasPrefix(trimmed, []byte("query {")) || bytes.HasPrefix(trimmed, []byte("mutation {")) || bytes.HasPrefix(trimmed, []byte("fragment ")) {
		return TypeGraphQL
	}

	code := skipCStyleComments(trimmed)
	if len(code) == 0 {
		return TypeNone
	}

	if bytes.HasPrefix(code, []byte("package ")) {
		if bytes.Contains(code, []byte("import (")) || bytes.Contains(code, []byte("import \"")) || bytes.Contains(code, []byte("func ")) {
			return TypeGo
		}

		if bytes.Contains(code, []byte("import java")) || bytes.Contains(code, []byte("public class ")) {
			return TypeJava
		}

		if bytes.Contains(code, []byte("import ")) || bytes.Contains(code, []byte("fun ")) || bytes.Contains(code, []byte("val ")) {
			return TypeKotlin
		}

		if bytes.Contains(code, []byte("import scala.")) || bytes.Contains(code, []byte("object ")) || bytes.Contains(code, []byte("trait ")) {
			return TypeScala
		}
	}

	if bytes.HasPrefix(code, []byte("#include <")) || bytes.HasPrefix(code, []byte("#include \"")) {
		if bytes.Contains(code, []byte("std::")) || bytes.Contains(code, []byte("class ")) || bytes.Contains(code, []byte("template <")) {
			return TypeCPP
		}

		return TypeC
	}

	if bytes.HasPrefix(code, []byte("#import <")) || bytes.HasPrefix(code, []byte("#import \"")) {
		return TypeObjectiveC
	}

	if bytes.HasPrefix(code, []byte("using System;")) || bytes.HasPrefix(code, []byte("namespace ")) {
		if bytes.Contains(code, []byte("public class ")) || bytes.Contains(code, []byte("public interface ")) {
			return TypeCSharp
		}
	}

	if bytes.HasPrefix(code, []byte("import Foundation")) || bytes.HasPrefix(code, []byte("import UIKit")) || bytes.HasPrefix(code, []byte("import SwiftUI")) {
		return TypeSwift
	}

	if bytes.HasPrefix(code, []byte("fn main()")) || bytes.HasPrefix(code, []byte("use std::")) || bytes.HasPrefix(code, []byte("pub fn ")) || bytes.HasPrefix(code, []byte("#![")) || bytes.HasPrefix(code, []byte("#[derive(")) || bytes.HasPrefix(code, []byte("#[allow(")) {
		return TypeRust
	}

	if bytes.HasPrefix(code, []byte("import ")) || bytes.HasPrefix(code, []byte("def ")) || bytes.HasPrefix(code, []byte("class ")) {
		if bytes.Contains(code, []byte("def ")) && bytes.Contains(code, []byte(":")) {
			return TypePython
		}
	}

	if bytes.HasPrefix(code, []byte("require '")) || bytes.HasPrefix(code, []byte("require \"")) || bytes.HasPrefix(code, []byte("require_relative ")) {
		if bytes.Contains(code, []byte("def ")) || bytes.Contains(code, []byte("class ")) || bytes.Contains(code, []byte("module ")) {
			return TypeRuby
		}
	}

	if bytes.HasPrefix(code, []byte("local ")) || bytes.HasPrefix(code, []byte("function ")) || bytes.HasPrefix(code, []byte("require ")) || bytes.HasPrefix(code, []byte("require(\"")) {
		if bytes.Contains(code, []byte("end")) || bytes.Contains(code, []byte(" then")) || bytes.Contains(code, []byte(" do")) || bytes.Contains(code, []byte(".lua")) {
			return TypeLua
		}
	}

	if bytes.HasPrefix(code, []byte("import 'package:")) || bytes.HasPrefix(code, []byte("import 'dart:")) {
		return TypeDart
	}

	if bytes.HasPrefix(code, []byte("library(")) || bytes.HasPrefix(code, []byte("require(")) {
		if bytes.Contains(code, []byte("<-")) || bytes.Contains(code, []byte("%>%")) {
			return TypeR
		}
	}

	if bytes.HasPrefix(code, []byte("const ")) || bytes.HasPrefix(code, []byte("let ")) || bytes.HasPrefix(code, []byte("var ")) || bytes.HasPrefix(code, []byte("import ")) {
		if bytes.Contains(code, []byte("interface ")) || bytes.Contains(code, []byte("type ")) || bytes.Contains(code, []byte(" as ")) || bytes.Contains(code, []byte(": string")) || bytes.Contains(code, []byte(": number")) || bytes.Contains(code, []byte(": boolean")) {
			if bytes.Contains(code, []byte("=>")) || bytes.Contains(code, []byte("console.log")) || bytes.Contains(code, []byte("from '")) || bytes.Contains(code, []byte("from \"")) {
				return TypeTypeScript
			}
		}

		if bytes.Contains(code, []byte("=>")) || bytes.Contains(code, []byte("console.log")) || bytes.Contains(code, []byte("function(")) || bytes.Contains(code, []byte("function ")) {
			return TypeJavaScript
		}
	}

	if bytes.HasPrefix(code, []byte("[")) {
		lineEnd := bytes.IndexByte(code, '\n')
		if lineEnd != -1 && bytes.Contains(code[:lineEnd], []byte("]")) {
			if bytes.Contains(code, []byte("=\"")) || bytes.Contains(code, []byte("= \"")) || bytes.Contains(code, []byte("['")) {
				return TypeTOML
			}

			return TypeINI
		}
	}

	if bytes.HasPrefix(code, []byte("CFLAGS")) || bytes.HasPrefix(code, []byte("TARGET")) || bytes.HasPrefix(code, []byte("all:")) || bytes.HasPrefix(code, []byte(".PHONY:")) {
		return TypeMakefile
	}

	if bytes.Contains(code, []byte("Write-Host ")) || bytes.Contains(code, []byte("Get-")) || bytes.Contains(code, []byte("Set-")) || bytes.Contains(code, []byte("Out-Null")) {
		if bytes.Contains(code, []byte("$")) && (bytes.Contains(code, []byte("-eq")) || bytes.Contains(code, []byte("-ne")) || bytes.Contains(code, []byte("param("))) {
			return TypePowerShell
		}
	}

	return TypeNone
}

func skipCStyleComments(b []byte) []byte {
	for len(b) > 0 {
		b = bytes.TrimSpace(b)
		if bytes.HasPrefix(b, []byte("//")) {
			idx := bytes.IndexByte(b, '\n')
			if idx == -1 {
				return nil
			}

			b = b[idx:]
		} else if bytes.HasPrefix(b, []byte("/*")) {
			idx := bytes.Index(b, []byte("*/"))
			if idx == -1 {
				return nil
			}

			b = b[idx+2:]
		} else {
			break
		}
	}

	return b
}

func passesTextLengthGate(b Buffer) bool {
	if b.Len() >= 16 {
		return true
	}

	return bytes.ContainsAny(b, " \t\r\n")
}

func isLikelyASCIIText(b Buffer) bool {
	limit := min(b.Len(), 4096)
	if limit == 0 {
		return false
	}

	var printable int

	target := b[:limit]

	for _, c := range target {
		if c == 0 {
			return false
		}

		if c == '\n' || c == '\r' || c == '\t' || (c >= 32 && c <= 126) {
			printable++
		}
	}

	return printable*100/limit >= 95
}

func isLikelyTextUTF8(b Buffer) bool {
	limit := min(b.Len(), 4096)
	if limit == 0 {
		return false
	}

	target := b[:limit]
	if !utf8.Valid(target) {
		return false
	}

	var printable int

	for _, c := range target {
		if c == 0 {
			return false
		}

		if c == '\n' || c == '\r' || c == '\t' || c >= 32 {
			printable++
		}
	}

	return printable*100/limit >= 90
}

type tiffByteOrder uint8

const (
	tiffLittleEndian tiffByteOrder = iota
	tiffBigEndian
)

func DetectTIFFSubtypes(b Buffer) *Metadata {
	if !isTIFFHeader(b) {
		if b.Has(0, []byte{'I', 'I', 'R', 'O', 0x08, 0x00}) || b.Has(0, []byte{'M', 'M', 'O', 'R', 0x00, 0x00}) {
			return &Metadata{Kind: KindOlympusRAWImage}
		}

		return nil
	}

	if b.Has(0, []byte{'I', 'I', 'U', 0x00}) {
		return &Metadata{Kind: KindTIFFImage, Type: TypePanasonicRAW}
	}

	if b.Has(0, []byte{'I', 'I', 0x2a, 0x00, 0x10, 0x00, 0x00, 0x00, 'C', 'R'}) {
		return &Metadata{Kind: KindCanonRAWImage, Type: TypeCanonRAWHE}
	}

	order, ifd0, ok := tiffHeaderInfo(b)
	if !ok {
		if b.Has(0, []byte{'I', 'I'}) {
			return &Metadata{Kind: KindTIFFImage, Type: TypeLittleEndian}
		}

		return &Metadata{Kind: KindTIFFImage, Type: TypeBigEndian}
	}

	if tiffHasTag(b, order, ifd0, 0xc612) {
		return &Metadata{Kind: KindTIFFImage, Type: TypeAdobeDNG}
	}

	makeValue, ok := tiffASCIIValueForTag(b, order, ifd0, 0x010f)
	if ok {
		if bytes.HasPrefix(makeValue, []byte("NIKON")) || bytes.HasPrefix(makeValue, []byte("Nikon")) {
			return &Metadata{Kind: KindTIFFImage, Type: TypeNikonRAW}
		}

		if bytes.HasPrefix(makeValue, []byte("OLYMPUS")) || bytes.HasPrefix(makeValue, []byte("Olympus")) {
			return &Metadata{Kind: KindOlympusRAWImage}
		}

		if bytes.HasPrefix(makeValue, []byte("PENTAX")) {
			return &Metadata{Kind: KindTIFFImage, Type: TypePentaxRAW}
		}

		if bytes.HasPrefix(makeValue, []byte("SONY")) {
			if bytes.Contains(makeValue, []byte("SR2")) {
				return &Metadata{Kind: KindTIFFImage, Type: TypeSonyRAWSR2}
			}

			return &Metadata{Kind: KindTIFFImage, Type: TypeSonyRAW}
		}
	}

	limit := min(b.Len(), 4096)
	data := b[:limit]

	if bytes.Contains(data, []byte("Nikon")) {
		return &Metadata{Kind: KindTIFFImage, Type: TypeNikonRAW}
	}

	if bytes.Contains(data, []byte("OLYMPUS")) || bytes.Contains(data, []byte("Olympus")) {
		return &Metadata{Kind: KindOlympusRAWImage}
	}

	if bytes.Contains(data, []byte("PENTAX")) {
		return &Metadata{Kind: KindTIFFImage, Type: TypePentaxRAW}
	}

	if bytes.Contains(data, []byte("SONY DSC")) {
		return &Metadata{Kind: KindTIFFImage, Type: TypeSonyRAW}
	}

	if bytes.Contains(data, []byte("SONY SR2")) {
		return &Metadata{Kind: KindTIFFImage, Type: TypeSonyRAWSR2}
	}

	if bytes.Contains(data, []byte("DNGVersion")) {
		return &Metadata{Kind: KindTIFFImage, Type: TypeAdobeDNG}
	}

	if b.Has(0, []byte{'I', 'I'}) {
		return &Metadata{Kind: KindTIFFImage, Type: TypeLittleEndian}
	}

	return &Metadata{Kind: KindTIFFImage, Type: TypeBigEndian}
}

func tiffHeaderInfo(b Buffer) (tiffByteOrder, uint32, bool) {
	if b.Has(0, []byte{'I', 'I', 42, 0}) {
		ifd0, ok := b.U32LE(4)
		if !ok || ifd0 >= uint32(b.Len()) {
			return 0, 0, false
		}

		return tiffLittleEndian, ifd0, true
	}

	if b.Has(0, []byte{'M', 'M', 0, 42}) {
		ifd0, ok := b.U32BE(4)
		if !ok || ifd0 >= uint32(b.Len()) {
			return 0, 0, false
		}

		return tiffBigEndian, ifd0, true
	}

	return 0, 0, false
}

func tiffHasTag(b Buffer, order tiffByteOrder, ifdOffset uint32, tag uint16) bool {
	count, ok := tiffU16(b, order, int(ifdOffset))
	if !ok {
		return false
	}

	entryBase := int(ifdOffset) + 2
	entryEnd := entryBase + int(count)*12
	if entryBase < 0 || entryEnd > b.Len() {
		return false
	}

	for i := range int(count) {
		entry := entryBase + i*12

		currentTag, ok := tiffU16(b, order, entry)
		if !ok {
			return false
		}

		if currentTag == tag {
			return true
		}
	}

	return false
}

func tiffASCIIValueForTag(b Buffer, order tiffByteOrder, ifdOffset uint32, tag uint16) ([]byte, bool) {
	count, ok := tiffU16(b, order, int(ifdOffset))
	if !ok {
		return nil, false
	}

	entryBase := int(ifdOffset) + 2
	entryEnd := entryBase + int(count)*12

	if entryBase < 0 || entryEnd > b.Len() {
		return nil, false
	}

	for i := range int(count) {
		entry := entryBase + i*12

		currentTag, ok := tiffU16(b, order, entry)
		if !ok || currentTag != tag {
			continue
		}

		fieldType, ok := tiffU16(b, order, entry+2)
		if !ok || fieldType != 2 {
			return nil, false
		}

		valueCount, ok := tiffU32(b, order, entry+4)
		if !ok || valueCount == 0 {
			return nil, false
		}

		if valueCount <= 4 {
			end := entry + 8 + int(valueCount)
			if end > b.Len() {
				return nil, false
			}

			return bytes.TrimRight(b[entry+8:end], "\x00"), true
		}

		valueOffset, ok := tiffU32(b, order, entry+8)
		if !ok {
			return nil, false
		}

		start := int(valueOffset)
		end := start + int(valueCount)

		if start < 0 || end > b.Len() {
			return nil, false
		}

		return bytes.TrimRight(b[start:end], "\x00"), true
	}

	return nil, false
}

func tiffU16(b Buffer, order tiffByteOrder, offset int) (uint16, bool) {
	if order == tiffLittleEndian {
		return b.U16LE(offset)
	}

	return b.U16BE(offset)
}

func tiffU32(b Buffer, order tiffByteOrder, offset int) (uint32, bool) {
	if order == tiffLittleEndian {
		return b.U32LE(offset)
	}

	return b.U32BE(offset)
}

func isTIFFHeader(b Buffer) bool {
	return b.Has(0, []byte{'I', 'I', 42, 0}) || b.Has(0, []byte{'M', 'M', 0, 42})
}

func DetectTorrent(b Buffer) *Metadata {
	if b.Len() < 32 || b[0] != 'd' {
		return nil
	}

	limit := min(b.Len(), 4096)
	data := b[:limit]

	if !bytes.Contains(data, []byte("8:announce")) || !bytes.Contains(data, []byte("4:info")) {
		return nil
	}

	return &Metadata{Kind: KindTorrentFile}
}

func DetectXMLSubtypes(b Buffer) *Metadata {
	limit := min(b.Len(), 1024)
	data := b[:limit]

	trimmed := bytes.TrimSpace(data)
	if len(trimmed) < 5 || trimmed[0] != '<' {
		return nil
	}

	isXML := bytes.HasPrefix(trimmed, []byte("<?xml")) || bytes.HasPrefix(trimmed, []byte("<!DOCTYPE"))

	if isXML || bytes.HasPrefix(trimmed, []byte("<svg")) {
		if bytes.Contains(data, []byte("<svg")) {
			return &Metadata{Kind: KindSVGImage, Confidence: ConfidenceMedium}
		}
	}

	if isXML {
		if bytes.Contains(data, []byte("<plist")) || bytes.Contains(data, []byte("<!DOCTYPE plist")) {
			return &Metadata{Kind: KindAppleXMLPropertyList, Confidence: ConfidenceMedium}
		}

		if bytes.Contains(data, []byte("<kml")) {
			return &Metadata{Kind: KindKeyholeMarkupLanguage, Confidence: ConfidenceMedium}
		}

		if bytes.Contains(data, []byte("<gpx")) {
			return &Metadata{Kind: KindGPSExchangeFormat, Confidence: ConfidenceMedium}
		}

		if bytes.Contains(data, []byte("<rss")) {
			return &Metadata{Kind: KindRSSFeed, Confidence: ConfidenceMedium}
		}

		if bytes.Contains(data, []byte("<feed")) {
			return &Metadata{Kind: KindAtomFeed, Confidence: ConfidenceMedium}
		}

		if bytes.Contains(data, []byte("<xsl:stylesheet")) || bytes.Contains(data, []byte("<xsl:transform")) {
			return &Metadata{Kind: KindXMLDocument, Type: TypeXSLTStylesheet, Confidence: ConfidenceMedium}
		}

		if bytes.Contains(data, []byte("<soap:Envelope")) {
			return &Metadata{Kind: KindSOAPMessage, Confidence: ConfidenceMedium}
		}

		return &Metadata{Kind: KindXMLDocument, Confidence: ConfidenceMedium}
	}

	return nil
}

func DetectZIPContainer(b Buffer) *Metadata {
	if b.Len() < 4 || string(b[:4]) != "PK\x03\x04" {
		return nil
	}

	var (
		hasManifest         bool
		hasDex              bool
		hasAppxManifest     bool
		hasAppxSignature    bool
		hasSketchMeta       bool
		hasSketchUser       bool
		hasSketchDoc        bool
		hasWord             bool
		hasExcel            bool
		hasPowerPoint       bool
		hasWordVBA          bool
		hasExcelVBA         bool
		hasPowerPointVBA    bool
		hasManifestMF       bool
		hasWebXML           bool
		hasAppXML           bool
		hasMinecraftMeta    bool
		hasFabricMod        bool
		hasForgeMod         bool
		hasLottieManifest   bool
		hasLottieAnimations bool
		hasPyTorchData      bool
		hasPyTorchVersion   bool
		hasComicInfo        bool
		firstFile           = true
	)

	limit := b.Len() - 30
	zipMagic := []byte{'P', 'K', 3, 4}

	for i := 0; i <= limit; {
		idx := bytes.Index(b[i:], zipMagic)
		if idx == -1 {
			break
		}

		i += idx

		nameLen, ok := b.U16LE(i + 26)
		if !ok || nameLen == 0 || i+30+int(nameLen) > b.Len() {
			i += 4
			continue
		}

		name := b[i+30 : i+30+int(nameLen)]

		if firstFile && string(name) == "mimetype" {
			compression, _ := b.U16LE(i + 8)
			extraLen, _ := b.U16LE(i + 28)
			dataLen, _ := b.U32LE(i + 18)
			dataStart := i + 30 + int(nameLen) + int(extraLen)
			dataEnd := dataStart + int(dataLen)

			if compression == 0 && dataStart >= 0 && int(dataLen) >= 0 && dataEnd >= dataStart && dataEnd <= b.Len() {
				switch string(b[dataStart:dataEnd]) {
				case "application/epub+zip":
					return &Metadata{Kind: KindZIPArchive, Type: TypeEPUBDocument}
				case "application/vnd.oasis.opendocument.text":
					return &Metadata{Kind: KindZIPArchive, Type: TypeOpenDocumentText}
				case "application/vnd.oasis.opendocument.spreadsheet":
					return &Metadata{Kind: KindZIPArchive, Type: TypeOpenDocumentSpreadsheet}
				case "application/vnd.oasis.opendocument.presentation":
					return &Metadata{Kind: KindZIPArchive, Type: TypeOpenDocumentPresentation}
				case "application/vnd.oasis.opendocument.graphics":
					return &Metadata{Kind: KindZIPArchive, Type: TypeOpenDocumentGraphics}
				case "application/vnd.oasis.opendocument.database":
					return &Metadata{Kind: KindZIPArchive, Type: TypeOpenDocumentDatabase}
				case "application/vnd.oasis.opendocument.formula":
					return &Metadata{Kind: KindZIPArchive, Type: TypeOpenDocumentFormula}
				case "application/vnd.oasis.opendocument.chart":
					return &Metadata{Kind: KindZIPArchive, Type: TypeOpenDocumentChart}
				case "application/vnd.oasis.opendocument.image":
					return &Metadata{Kind: KindZIPArchive, Type: TypeOpenDocumentImage}
				case "application/x-krita":
					return &Metadata{Kind: KindZIPArchive, Type: TypeKritaDocument}
				case "image/openraster":
					return &Metadata{Kind: KindZIPArchive, Type: TypeOpenRasterImage}
				}
			}
		}

		firstFile = false

		if matchASCII(name, "androidmanifest.xml") {
			hasManifest = true
		} else if hasSuffixASCII(name, ".dex") || matchASCII(name, "classes.dex") {
			hasDex = true
		} else if matchASCII(name, "appxmanifest.xml") {
			hasAppxManifest = true
		} else if matchASCII(name, "appxsignature.p7x") {
			hasAppxSignature = true
		} else if matchASCII(name, "document.json") {
			hasSketchDoc = true
		} else if matchASCII(name, "meta.json") {
			hasSketchMeta = true
		} else if matchASCII(name, "user.json") {
			hasSketchUser = true
		} else if matchASCII(name, "modules") {
			return &Metadata{Kind: KindZIPArchive, Type: TypeNone}
		} else if matchASCII(name, "meta-inf/manifest.mf") {
			hasManifestMF = true
		} else if matchASCII(name, "web-inf/web.xml") {
			hasWebXML = true
		} else if matchASCII(name, "meta-inf/application.xml") {
			hasAppXML = true
		} else if matchASCII(name, "pack.mcmeta") {
			hasMinecraftMeta = true
		} else if matchASCII(name, "fabric.mod.json") {
			hasFabricMod = true
		} else if matchASCII(name, "mcmod.info") || matchASCII(name, "meta-inf/mods.toml") {
			hasForgeMod = true
		} else if matchASCII(name, "model.weights.h5") {
			return &Metadata{Kind: KindZIPArchive, Type: TypeKerasModel}
		} else if hasSuffixASCII(name, "/data.pkl") || matchASCII(name, "data.pkl") {
			hasPyTorchData = true
		} else if hasSuffixASCII(name, "/version") || matchASCII(name, "version") {
			hasPyTorchVersion = true
		} else if matchASCII(name, "main.lua") {
			return &Metadata{Kind: KindZIPArchive, Type: TypeLOVEGame}
		} else if matchASCII(name, "doc.kml") {
			return &Metadata{Kind: KindZIPArchive, Type: TypeKMZArchive}
		} else if hasSuffixASCII(name, ".dist-info/wheel") {
			return &Metadata{Kind: KindZIPArchive, Type: TypePythonWheel}
		} else if matchASCII(name, "manifest.json") {
			hasLottieManifest = true

			if bytes.Contains(b, []byte("xapk_version")) {
				return &Metadata{Kind: KindZIPArchive, Type: TypeAndroidPackageX}
			}

			if bytes.Contains(b, []byte("browser_specific_settings")) {
				return &Metadata{Kind: KindZIPArchive, Type: TypeFirefoxExtension}
			}
		} else if matchASCII(name, "install.rdf") {
			return &Metadata{Kind: KindZIPArchive, Type: TypeFirefoxExtension}
		} else if hasPrefixASCII(name, "animations/") {
			hasLottieAnimations = true
		} else if hasPrefixASCII(name, "payload/") {
			return &Metadata{Kind: KindZIPArchive, Type: TypeIOSApplicationArchive}
		} else if matchASCII(name, "bundleconfig.pb") {
			return &Metadata{Kind: KindZIPArchive, Type: TypeAndroidAppBundle}
		} else if matchASCII(name, "toc.pb") {
			return &Metadata{Kind: KindZIPArchive, Type: TypeAndroidSplitAPKSet}
		} else if bytes.Contains(name, []byte("apex_manifest")) {
			return &Metadata{Kind: KindZIPArchive, Type: TypeAndroidSystemPackage}
		} else if matchASCII(name, "extension.vsixmanifest") {
			return &Metadata{Kind: KindZIPArchive, Type: TypeVisualStudioExtension}
		} else if matchASCII(name, "3d/3dmodel.model") {
			return &Metadata{Kind: KindZIPArchive, Type: Type3MFDocument}
		} else if hasSuffixASCII(name, ".nuspec") {
			return &Metadata{Kind: KindZIPArchive, Type: TypeNuGetPackage}
		} else if matchASCII(name, "comicinfo.xml") {
			hasComicInfo = true
		} else if matchASCII(name, "metadata/buildversionhistory.plist") || hasPrefixASCII(name, "index/document.iwa") {
			return &Metadata{Kind: KindAppleiWorkDocument}
		}

		if hasPrefixASCII(name, "word/") {
			hasWord = true
		} else if hasPrefixASCII(name, "xl/") {
			hasExcel = true
		} else if hasPrefixASCII(name, "ppt/") {
			hasPowerPoint = true
		}

		if matchASCII(name, "word/vbaproject.bin") {
			hasWordVBA = true
		} else if matchASCII(name, "xl/vbaproject.bin") {
			hasExcelVBA = true
		} else if matchASCII(name, "ppt/vbaproject.bin") {
			hasPowerPointVBA = true
		}

		i += 30 + int(nameLen)
	}

	limitSearch := min(b.Len(), 32768)
	searchArea := b[:limitSearch]

	if hasWordVBA {
		return &Metadata{Kind: KindZIPArchive, Type: TypeMicrosoftWordMacroEnabledDocument}
	}

	if hasExcelVBA {
		return &Metadata{Kind: KindZIPArchive, Type: TypeMicrosoftExcelMacroEnabledWorkbook}
	}

	if hasPowerPointVBA {
		return &Metadata{Kind: KindZIPArchive, Type: TypeMicrosoftPowerPointMacroEnabledPresentation}
	}

	if bytes.Contains(searchArea, []byte("application/vnd.ms-word.document.macroEnabled.main+xml")) {
		return &Metadata{Kind: KindZIPArchive, Type: TypeMicrosoftWordMacroEnabledDocument}
	}

	if bytes.Contains(searchArea, []byte("application/vnd.openxmlformats-officedocument.wordprocessingml.template.main+xml")) {
		return &Metadata{Kind: KindZIPArchive, Type: TypeMicrosoftWordTemplate}
	}

	if bytes.Contains(searchArea, []byte("application/vnd.ms-word.template.macroEnabledTemplate.main+xml")) {
		return &Metadata{Kind: KindZIPArchive, Type: TypeMicrosoftWordMacroEnabledTemplate}
	}

	if hasWord {
		return &Metadata{Kind: KindZIPArchive, Type: TypeMicrosoftWordDocument}
	}

	if bytes.Contains(searchArea, []byte("application/vnd.ms-excel.sheet.macroEnabled.main+xml")) {
		return &Metadata{Kind: KindZIPArchive, Type: TypeMicrosoftExcelMacroEnabledWorkbook}
	}

	if bytes.Contains(searchArea, []byte("application/vnd.openxmlformats-officedocument.spreadsheetml.template.main+xml")) {
		return &Metadata{Kind: KindZIPArchive, Type: TypeMicrosoftExcelTemplate}
	}

	if bytes.Contains(searchArea, []byte("application/vnd.ms-excel.template.macroEnabled.main+xml")) {
		return &Metadata{Kind: KindZIPArchive, Type: TypeMicrosoftExcelMacroEnabledTemplate}
	}

	if bytes.Contains(searchArea, []byte("application/vnd.ms-excel.addin.macroEnabled.main+xml")) {
		return &Metadata{Kind: KindZIPArchive, Type: TypeMicrosoftExcelAddIn}
	}

	if hasExcel {
		return &Metadata{Kind: KindZIPArchive, Type: TypeMicrosoftExcelWorkbook}
	}

	if bytes.Contains(searchArea, []byte("application/vnd.ms-powerpoint.presentation.macroEnabled.main+xml")) {
		return &Metadata{Kind: KindZIPArchive, Type: TypeMicrosoftPowerPointMacroEnabledPresentation}
	}

	if bytes.Contains(searchArea, []byte("application/vnd.openxmlformats-officedocument.presentationml.template.main+xml")) {
		return &Metadata{Kind: KindZIPArchive, Type: TypeMicrosoftPowerPointTemplate}
	}

	if bytes.Contains(searchArea, []byte("application/vnd.ms-powerpoint.template.macroEnabled.main+xml")) {
		return &Metadata{Kind: KindZIPArchive, Type: TypeMicrosoftPowerPointMacroEnabledTemplate}
	}

	if bytes.Contains(searchArea, []byte("application/vnd.openxmlformats-officedocument.presentationml.slideshow.main+xml")) {
		return &Metadata{Kind: KindZIPArchive, Type: TypeMicrosoftPowerPointSlideshow}
	}

	if bytes.Contains(searchArea, []byte("application/vnd.ms-powerpoint.slideshow.macroEnabled.main+xml")) {
		return &Metadata{Kind: KindZIPArchive, Type: TypeMicrosoftPowerPointMacroEnabledSlideshow}
	}

	if bytes.Contains(searchArea, []byte("application/vnd.ms-powerpoint.addin.macroEnabled.main+xml")) {
		return &Metadata{Kind: KindZIPArchive, Type: TypeMicrosoftPowerPointAddIn}
	}

	if hasPowerPoint {
		return &Metadata{Kind: KindZIPArchive, Type: TypeMicrosoftPowerPointPresentation}
	}

	if bytes.Contains(searchArea, []byte("application/vnd.ms-xpsdocument.document+xml")) {
		return &Metadata{Kind: KindZIPArchive, Type: TypeXMLPaperSpecification}
	}

	if hasManifest {
		if hasDex {
			return &Metadata{Kind: KindZIPArchive, Type: TypeAndroidPackage}
		}

		return &Metadata{Kind: KindZIPArchive, Type: TypeAndroidArchive}
	}

	if hasAppxManifest {
		if hasAppxSignature {
			return &Metadata{Kind: KindZIPArchive, Type: TypeMSIXPackage}
		}

		return &Metadata{Kind: KindZIPArchive, Type: TypeAPPXPackage}
	}

	if hasSketchDoc && (hasSketchMeta || hasSketchUser) {
		if bytes.Contains(searchArea, []byte("com.bohemiancoding.sketch")) || bytes.Contains(searchArea, []byte("com.sketch3")) {
			return &Metadata{Kind: KindSketchDocument}
		}
	}

	if hasManifestMF {
		if hasWebXML {
			return &Metadata{Kind: KindZIPArchive, Type: TypeJavaWebArchive}
		}

		if hasAppXML {
			return &Metadata{Kind: KindZIPArchive, Type: TypeJavaEnterpriseArchive}
		}

		if hasFabricMod {
			return &Metadata{Kind: KindZIPArchive, Type: TypeFabricMod}
		}

		if hasForgeMod {
			return &Metadata{Kind: KindZIPArchive, Type: TypeForgeMod}
		}

		if hasMinecraftMeta {
			return &Metadata{Kind: KindZIPArchive, Type: TypeMinecraftResourcePack}
		}

		return &Metadata{Kind: KindZIPArchive, Type: TypeJavaArchive}
	}

	if hasLottieManifest && hasLottieAnimations {
		return &Metadata{Kind: KindLottieAnimation}
	}

	if hasPyTorchData && hasPyTorchVersion {
		return &Metadata{Kind: KindZIPArchive, Type: TypePyTorchModel}
	}

	if hasComicInfo {
		return &Metadata{Kind: KindComicBookArchive, Type: TypeCBZ}
	}

	return &Metadata{Kind: KindZIPArchive}
}

func matchASCII(b []byte, lower string) bool {
	if len(b) != len(lower) {
		return false
	}

	for i := range b {
		c := b[i]
		if c >= 'A' && c <= 'Z' {
			c += 32
		}

		if c != lower[i] {
			return false
		}
	}

	return true
}

func hasSuffixASCII(b []byte, lowerSuffix string) bool {
	if len(b) < len(lowerSuffix) {
		return false
	}

	return matchASCII(b[len(b)-len(lowerSuffix):], lowerSuffix)
}

func hasPrefixASCII(b []byte, lowerPrefix string) bool {
	if len(b) < len(lowerPrefix) {
		return false
	}

	return matchASCII(b[:len(lowerPrefix)], lowerPrefix)
}

func DetectZlib(b Buffer) *Metadata {
	if b.Len() < 2 {
		return nil
	}

	cmf := b[0]
	flg := b[1]

	if cmf&0x0f != 8 {
		return nil
	}

	if cmf>>4 > 7 {
		return nil
	}

	if (uint16(cmf)<<8|uint16(flg))%31 != 0 {
		return nil
	}

	return &Metadata{
		Kind:       KindZlibData,
		Confidence: ConfidenceMedium,
	}
}
